### ISSUE TITLE
Control from Google Home?

### ISSUE THREAD

**Issue by arrmo** [tagyoureit/nodejs-poolController#1]
OK, have to ask - as the wife just bought one of these ... :).

Any chance we can interface to / control this from Google Home?

Feel free to close if this is nuts!

**Comment by tagyoureit** [comment]
If she wants to buy me one, too, I'll be happy to get it going!  lol.  The answer is yes, I would love to have this integration, but it's a bit beyond my reach now.  

We'll leave it open and I flagged it 'help wanted'.

**Comment by triorbonk** [comment]
I do much of my GH integration through my ISY.  

But to relay information about the pool IE: Temp, clor, etc.  You would need to following this tutorial. 
https://codelabs.developers.google.com/codelabs/actions-1/index.html?index=..%2F..index#0

**Comment by tagyoureit** [comment]
I still don't have a Google Home (nor an ISY).  Would be great to have some community help on this one.  :)

**Comment by triorbonk** [comment]
I have started working on this.  Will post info as I figure it out.

Eric
