### ISSUE TITLE
reset layout on web scren causing read errors in www/bootstrap/configClient.json

### ISSUE THREAD

**Issue by mark-hoy** [tagyoureit/nodejs-poolController#101]
### Expected behavior and actual behavior
No errors thrown

### Steps to reproduce the problem
unzip 5.1.1 release
npm install
npm audit fix
npm start

### Specifications

1. What version of the code are you using?
5.1.1

2. All output from the file log (See [packet capture](https://githu.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution))

3. Any errors that are in the console
15:45:07.497 INFO updateVersionNotificationAsync requested from Socket.io.  value:
15:45:07.606 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.611 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined
15:45:07.624 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.628 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined
15:45:07.634 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.637 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined
15:45:07.643 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.647 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined
15:45:07.653 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.656 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined
15:45:07.662 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.666 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined
15:45:07.672 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.676 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined
15:45:07.681 WARN Error reading /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json file: Unexpected end of JSON input
15:45:07.685 WARN Error updating bootstrap /home/mhoy/src/nodejs-poolController-5.1.1/src/www/bootstrap/configClient.json: Cannot read property 'panelState' of undefined

4. Your config.json or in-use configuration file
straight from a startup

5. Your pool equipment
Pentair easytouch 8, IC40, Intelliflow pump

**Comment by tagyoureit** [comment]
This should be fixed in the latest 5.2-DEV branch.
