### ISSUE TITLE
heater modes : off , heater

### ISSUE THREAD

**Issue by omo22** [tagyoureit/nodejs-poolController#1013]
## 💥 Proposal
add heater modes : off , heater
### What feature you'd like to see
add heater modes : off , heater
(A clear and concise description of what the proposal is.)
add under feature device trigger 
## Motivation

it is better to have full heater control in one same area of thermostat UI dash panel
e.g clicking off will make heater pwr 120v switch off
e.g clicking heat will make pwr 120v sw on and start thermostat auto control 

if mode is OFF then heater 120v power turned off and heater flow valve off
if mode is heater then heater pwr 120v  and heater flow valve are on
if thermostat is triggered while mode=heater then fireman sw relay is toggling  (keeping heater valve and heater pwr unaffected 
on)
the current software will toggle fireman sw only and had to add circuit to manually controlling heater pwr and heater flow vlave

(Please outline the motivation for the proposal. It's interesting knowing what people are working on and also could help community members make suggestions for work-arounds until the feature is built)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by tagyoureit** [comment]
There's no need for this.  If you set up the connection to REM from the heater config page, the heater will turn on regardless if the pool or spa heat setpoint is exceeded and the heat mode is heater.  You don't need a separate circuit for this.

![image](https://github.com/user-attachments/assets/bd0d23ce-88d6-40c1-a2d6-3da750df396b)
