### ISSUE TITLE
Lots of undefined and can't write to serial bus

### ISSUE THREAD

**Issue by csblank** [tagyoureit/nodejs-poolController#103]
Having problems writing to serial bus.  I have a Waveshare HAT RS485.  I have a Pentair Easy Touch Controller with a heat pump and Intellibright light.

> nodejs-poolcontroller@5.1.0 start /Pubs/nodejs-poolController-master
> node src/index.js

19:34:08.260 INFO Starting up express server, http (port 3000)
19:34:08.386 INFO Starting up MDNS server
19:34:08.502 INFO initializing logger
19:34:09.118 INFO Configuration settings:
19:34:09.120 INFO Settings:

*******************************
 Version: 5.1.0
 
Configuration file name: config.json
*******************************{
    "version": "5.1.0",
    "equipment": {
        "controller": {
            "intellicom": {
                "installed": 0,
                "friendlyName": ""
            },
            "intellitouch": {
                "installed": 1,
                "friendlyName": ""
            },
            "virtual": {
                "pumpController": "default",
                "chlorinatorController": "default"
            }
        },
        "circuit": {
            "hideAux": false,
            "friendlyName": {
                "1": "",
                "2": "",
                "3": "",
                "4": "",
                "5": "",
                "6": "",
                "7": "",
                "8": "",
                "9": "",
                "10": "",
                "11": "",
                "12": "",
                "13": "",
                "14": "",
                "15": "",
                "16": "",
                "17": "",
                "18": "",
                "19": "",
                "20": ""
            }
        },
        "chlorinator": {
            "installed": 1,
            "desiredOutput": {
                "pool": -1,
                "spa": -1
            },
            "friendlyName": "",
            "id": {
                "productName": ""
            }
        },
        "pump": {
            "1": {
                "type": "VS",
                "externalProgram": {
                    "1": -1,
                    "2": -1,
                    "3": -1,
                    "4": -1
                },
                "friendlyName": ""
            },
            "2": {
                "type": "none",
                "externalProgram": {
                    "1": -1,
                    "2": -1,
                    "3": -1,
                    "4": -1
                },
                "friendlyName": ""
            }
        },
        "intellichem": {
            "installed": 0
        },
        "spa": {
            "installed": 0
        },
        "solar": {
            "installed": 0
        }
    },
    "poolController": {
        "appAddress": 33,
        "http": {
            "enabled": 1,
            "expressPort": 3000,
            "redirectToHttps": 0,
            "expressAuth": 0,
            "expressAuthFile": "/users.htpasswd"
        },
        "https": {
            "enabled": 0,
            "expressPort": 3001,
            "expressAuth": 0,
            "expressAuthFile": "/users.htpasswd",
            "expressKeyFile": "/data/server.key",
            "expressCertFile": "/data/server.crt"
        },
        "network": {
            "rs485Port": "/dev/ttyAMA0",
            "netConnect": 0,
            "netHost": "pool-ctrl-pi",
            "netPort": 9801,
            "inactivityRetry": 10
        },
        "log": {
            "logLevel": "info",
            "socketLogLevel": "info",
            "logPumpMessages": 0,
            "logDuplicateMessages": 0,
            "logConsoleNotDecoded": 0,
            "logConfigMessages": 0,
            "logMessageDecoding": 0,
            "logChlorinator": 0,
            "logIntellichem": 0,
            "logPacketWrites": 0,
            "logPumpTimers": 0,
            "logReload": 0,
            "logApi": 0,
            "logIntellibrite": 0,
            "fileLog": {
                "enable": 0,
                "fileLogLevel": "silly",
                "fileName": "output.log"
            }
        },
        "database": {
            "influx": {
                "enabled": 0,
                "host": "localhost",
                "port": 8086,
                "database": "pool"
            }
        }
    },
    "meta": {
        "notifications": {
            "version": {
                "remote": {
                    "version": "5.1.1",
                    "tag_name": "v5.1.1",
                    "dismissUntilNextRemoteVersionBump": false
                }
            }
        }
    },
    "integrations": {}
}
19:34:09.366 INFO Starting up SSDP server
19:34:09.964 WARN Update available!  Version 5.1.1 can be installed.  You have 5.1.0
19:34:11.123 INFO Queueing messages to retrieve configuration from Intellitouch
19:34:11.216 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,41,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,98,0,0,0,4,0,0,134,245,3,13,4,31
19:34:13.613 WARN Error writing controller packet 'Get SW Version' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,253,1,0,1,213
19:34:16.001 ERROR Aborting controller packet Get SW Version.  Tried 10 times to write 255,0,255,165,1,16,33,253,1,0,1,213
19:34:16.005 WARN Setting logging level to Debug.  Will revert to previous level in 2 minutes.
19:34:18.571 WARN Error writing controller packet 'Get Date/Time' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,197,1,0,1,157
19:34:20.958 ERROR Aborting controller packet Get Date/Time.  Tried 10 times to write 255,0,255,165,1,16,33,197,1,0,1,157
19:34:23.522 WARN Error writing controller packet 'Get Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:34:25.910 ERROR Aborting controller packet Get Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:34:28.474 WARN Error writing controller packet 'Get Valves' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,221,1,0,1,181
19:34:30.863 ERROR Aborting controller packet Get Valves.  Tried 10 times to write 255,0,255,165,1,16,33,221,1,0,1,181
19:34:33.440 WARN Error writing controller packet 'Get Settings, Heat Mode?' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,232,1,0,1,192
19:34:35.828 ERROR Aborting controller packet Get Settings, Heat Mode?.  Tried 10 times to write 255,0,255,165,1,16,33,232,1,0,1,192
19:34:37.429 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,42,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,98,0,0,0,4,0,0,134,245,3,13,4,32
19:34:38.393 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,0,1,162
19:34:40.782 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,0,1,162
19:34:43.350 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,1,1,163
19:34:45.742 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,1,1,163
19:34:48.310 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,2,1,164
19:34:50.701 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,2,1,164
19:34:53.266 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,3,1,165
19:34:55.666 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,3,1,165
19:34:58.229 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,4,1,166
19:35:00.465 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,4,1,166
19:35:03.029 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,5,1,167
19:35:05.416 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,5,1,167
19:35:07.979 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,6,1,168
19:35:10.367 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,6,1,168
19:35:12.928 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,7,1,169
19:35:15.315 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,7,1,169
19:35:17.879 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,8,1,170
19:35:20.268 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,8,1,170
19:35:22.831 WARN Error writing controller packet 'Get Custom Name' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,202,1,9,1,171
19:35:25.219 ERROR Aborting controller packet Get Custom Name.  Tried 10 times to write 255,0,255,165,1,16,33,202,1,9,1,171
19:35:27.780 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,1,1,164
19:35:30.168 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,1,1,164
19:35:32.733 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,2,1,165
19:35:35.121 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,2,1,165
19:35:37.686 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,3,1,166
19:35:40.073 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,3,1,166
19:35:40.859 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,43,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,98,0,0,0,4,0,0,134,245,3,13,4,33
19:35:42.637 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,4,1,167
19:35:45.027 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,4,1,167
19:35:47.592 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,5,1,168
19:35:49.979 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,5,1,168
19:35:52.540 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,6,1,169
19:35:54.927 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,6,1,169
19:35:57.489 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,7,1,170
19:35:58.373 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,7,1,170
19:36:00.934 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,8,1,171
19:36:03.318 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,8,1,171
19:36:05.878 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,9,1,172
19:36:08.269 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,9,1,172
19:36:10.828 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,10,1,173
19:36:13.213 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,10,1,173
19:36:15.777 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,11,1,174
19:36:16.011 WARN Setting logging level to info
19:36:18.161 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,11,1,174
19:36:18.164 WARN Setting logging level to Debug.  Will revert to previous level in 2 minutes.
19:36:20.727 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,12,1,175
19:36:23.111 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,12,1,175
19:36:25.673 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,13,1,176
19:36:28.056 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,13,1,176
19:36:30.620 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,14,1,177
19:36:33.005 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,14,1,177
19:36:35.567 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,15,1,178
19:36:37.951 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,15,1,178
19:36:40.237 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,44,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,98,0,0,0,4,0,0,134,245,3,13,4,34
19:36:40.512 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,16,1,179
19:36:42.896 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,16,1,179
19:36:45.456 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,17,1,180
19:36:47.841 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,17,1,180
19:36:50.401 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,18,1,181
19:36:52.785 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,18,1,181
19:36:55.345 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,19,1,182
19:36:57.729 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,19,1,182
19:36:58.547 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,44,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,97,0,0,0,4,0,0,134,245,3,13,4,33
19:36:59.391 WARN Error writing controller packet 'Get Circuit Name/Function' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,203,1,20,1,183
19:37:00.281 ERROR Aborting controller packet Get Circuit Name/Function.  Tried 10 times to write 255,0,255,165,1,16,33,203,1,20,1,183
19:37:02.842 WARN Error writing controller packet 'Get Light group/positions' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,231,1,0,1,191
19:37:05.227 ERROR Aborting controller packet Get Light group/positions.  Tried 10 times to write 255,0,255,165,1,16,33,231,1,0,1,191
19:37:07.787 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,1,1,170
19:37:10.172 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,1,1,170
19:37:12.733 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,2,1,171
19:37:15.120 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,2,1,171
19:37:17.683 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,3,1,172
19:37:20.068 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,3,1,172
19:37:22.634 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,4,1,173
19:37:25.019 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,4,1,173
19:37:27.579 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,5,1,174
19:37:29.965 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,5,1,174
19:37:32.525 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,6,1,175
19:37:34.915 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,6,1,175
19:37:37.476 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,7,1,176
19:37:37.586 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,45,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,33
19:37:39.860 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,7,1,176
19:37:42.421 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,8,1,177
19:37:44.806 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,8,1,177
19:37:47.368 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,9,1,178
19:37:49.753 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,9,1,178
19:37:52.313 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,10,1,179
19:37:54.698 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,10,1,179
19:37:57.259 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,11,1,180
19:37:59.643 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,11,1,180
19:38:01.002 WARN Error writing controller packet 'Get Schedule' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,209,1,12,1,181
19:38:01.886 ERROR Aborting controller packet Get Schedule.  Tried 10 times to write 255,0,255,165,1,16,33,209,1,12,1,181
19:38:04.446 WARN Error writing controller packet 'Get Pump Config (Extended)' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,219,1,1,1,180
19:38:06.829 ERROR Aborting controller packet Get Pump Config (Extended).  Tried 10 times to write 255,0,255,165,1,16,33,219,1,1,1,180
19:38:18.178 WARN Setting logging level to info
19:38:22.802 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,45,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,95,0,0,0,4,0,0,134,245,3,13,4,32
19:38:36.966 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,46,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,95,0,0,0,4,0,0,134,245,3,13,4,33
19:39:38.370 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,47,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,95,0,0,0,4,0,0,134,245,3,13,4,34
19:40:37.749 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,48,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,95,0,0,0,4,0,0,134,245,3,13,4,35
19:41:12.847 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,48,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,36
19:41:37.133 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,49,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,37
19:42:38.523 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,50,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,38
19:42:45.544 INFO 
        {"text":"User request to update pool heat set point to 83: 165,1,16,33,136,4,83,100,4,0,2,30","status":"OFF","value":83}
19:42:47.934 WARN Error writing controller packet 'Set Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,136,4,83,100,4,0,2,30
19:42:50.318 ERROR Aborting controller packet Set Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,136,4,83,100,4,0,2,30
19:42:50.320 WARN Setting logging level to Debug.  Will revert to previous level in 2 minutes.
19:42:52.881 WARN Error writing controller packet 'Get Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:42:55.265 ERROR Aborting controller packet Get Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:43:37.908 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,51,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,39
19:44:39.311 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,52,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,40
19:44:50.325 WARN Setting logging level to info
19:45:07.973 INFO User request to update pool heat mode to Heater
19:45:10.209 WARN Error writing controller packet 'Set Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,136,4,84,100,5,0,2,32
19:45:11.090 ERROR Aborting controller packet Set Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,136,4,84,100,5,0,2,32
19:45:11.093 WARN Setting logging level to Debug.  Will revert to previous level in 2 minutes.
19:45:13.653 WARN Error writing controller packet 'Get Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:45:16.036 ERROR Aborting controller packet Get Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:45:37.000 DEBUG Msg# 367   Pool/Spa heat set point HAS NOT CHANGED:  pool heat mode: OFF @ 84 degrees; spa heat mode Heater at 100 degrees
19:45:38.681 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,53,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,41
19:46:15.361 DEBUG Setting config_client properties:  panelState debug state hidden
19:46:15.370 VERBOSE Updated configClient.json.
19:46:17.831 DEBUG Setting config_client properties:  panelState debug state visible
19:46:17.837 VERBOSE Updated configClient.json.
19:46:25.261 INFO updateVersionNotificationAsync requested from Socket.io.  value: true
19:46:25.270 VERBOSE Updated version notification settings {"version":{"remote":{"version":"5.1.1","tag_name":"v5.1.1","dismissUntilNextRemoteVersionBump":true}}}
19:46:44.133 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,54,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,42
19:46:59.992 INFO 
        {"text":"User request to update pool heat set point to 83: 165,1,16,33,136,4,83,100,4,0,2,30","status":"OFF","value":83}
19:47:02.381 WARN Error writing controller packet 'Set Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,136,4,83,100,4,0,2,30
19:47:04.366 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,54,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,97,0,0,0,4,0,0,134,245,3,13,4,43
19:47:04.764 ERROR Aborting controller packet Set Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,136,4,83,100,4,0,2,30
19:47:07.323 WARN Error writing controller packet 'Get Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:47:09.707 ERROR Aborting controller packet Get Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,200,1,0,1,160
19:47:11.097 WARN Setting logging level to info
19:47:37.430 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,55,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,97,0,0,0,4,0,0,134,245,3,13,4,44
19:47:57.663 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,55,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,96,0,0,0,4,0,0,134,245,3,13,4,43
19:48:05.758 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,55,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,97,0,0,0,4,0,0,134,245,3,13,4,44
19:48:38.837 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,56,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,97,0,0,0,4,0,0,134,245,3,13,4,45
19:49:38.225 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,57,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,97,0,0,0,4,0,0,134,245,3,13,4,46
19:50:39.621 INFO Received valve status packet.  
        Possible association with undefined. 
          valve data: 165,1,15,16,2,29,15,58,32,0,0,0,0,0,0,32,0,0,0,4,87,87,32,0,97,0,0,0,4,0,0,134,245,3,13,4,47

**Comment by tagyoureit** [comment]
You need to set `intellitouch: 0`.  Intellitouch has settings that the Easy Touch doesn't have and those are the messages that the app is trying to send.

**Comment by csblank** [comment]
I made the change you suggested and now, I'm getting the following messages.

00:37:09.771 INFO Starting up SSDP server
00:37:10.389 WARN Update available!  Version 5.1.1 can be installed.  You have 5.1.0
00:37:11.021 INFO No pool controller (Intellitouch or IntelliComII) detected.  No configuration request messages sent.
00:37:13.889 INFO Received valve status packet.
        Possible association with undefined.
          valve data: 165,1,15,16,2,29,20,44,32,0,0,0,0,0,0,32,0,0,0,4,86,86,32,0,80,0,0,0,4,0,0,134,245,3,13,4,19
00:37:15.955 WARN Error writing pump packet 'Pump control panel' to serial bus.  Tried 5 times to write 255,0,255,165,0,96,33,4,1,255,2,42
00:37:18.343 ERROR Aborting pump packet Pump control panel.  Tried 10 times to write 255,0,255,165,0,96,33,4,1,255,2,42
00:37:18.347 WARN Setting logging level to Debug.  Will revert to previous level in 2 minutes.
00:37:20.913 WARN Error writing pump packet 'Pump Status' to serial bus.  Tried 5 times to write 255,0,255,165,0,96,33,7,0,1,45
00:37:23.302 ERROR Aborting pump packet Pump Status.  Tried 10 times to write 255,0,255,165,0,96,33,7,0,1,45
00:37:25.867 WARN Error writing chlorinator packet 'Set Salt %' to serial bus.  Tried 5 times to write 16,2,80,17,0,115,16,3
00:37:28.254 ERROR Aborting chlorinator packet Set Salt %.  Tried 10 times to write 16,2,80,17,0,115,16,3

**Comment by tagyoureit** [comment]
Set both of these to `never`...
> "virtual": {
"pumpController": "default",
"chlorinatorController": "default"

**Comment by csblank** [comment]
I set the pump controller to "never".  I left the chlorinator set to default, As I have a "Pentair IntelliChlor IC40".  Now, when I start the program I get the following. I was trying to change the temperature.  Seems like I'm having issue writing to the serial bus.  Its a 2-wire setup so perhaps its something with signaling the "transmit".  Wasn't sure if you had any knowledge on RS485 directly.  I'm using a Raspberry PI HAT.  I know that I have the DT+ and DT- right, else I couldn't ready any values.

14:05:17.217 INFO 
        {"text":"User request to update pool heat set point to 83: 165,1,16,33,136,4,83,100,4,0,2,30","status":"OFF","value":83}
14:05:19.608 WARN Error writing controller packet 'Set Heat/Temperature' to serial bus.  Tried 5 times to write 255,0,255,165,1,16,33,136,4,83,100,4,0,2,30
14:05:22.007 ERROR Aborting controller packet Set Heat/Temperature.  Tried 10 times to write 255,0,255,165,1,16,33,136,4,83,100,4,0,2,30

**Comment by tagyoureit** [comment]
I'm not sure how the Easy Touch handles heat.  It could be a different command.  Do you have any remote panels/controllers attached to your Easy Touch?  If so, I would suggest downloading the 5.2-DEV branch and using the new [capture tool](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution).  When you are recording you would change the heat and capture what the remote controller sends to Easy Touch and we could add it to the system.  Otherwise, you'll most likely be using this app in a read-only mode for many aspects.

**Comment by MaxVonEvil** [comment]
This is an old closed issue, yet I ran into the same issue. 
In my case it turned out it was the internal serial interface which was mucking things up. To fix:
1) sudo raspi-config
2) under interfacing options, serial, answer no to both questions to disable the serial interface.

@tagyoureit  - you might want to add this to the installation instructions?

**Comment by tagyoureit** [comment]
Thanks... added to the [wiki](https://github.com/tagyoureit/nodejs-poolController/wiki/RS-485-Adapter-Details#raspi).
