### ISSUE TITLE
Intellibrite mode changes aren't reflected when set with API

### ISSUE THREAD

**Issue by leftyfl1p** [tagyoureit/nodejs-poolController#106]
Setting the Intellibrite mode with `http://host/light/mode/###` won't update the light state in the API after the light changes go through.

Steps to reproduce:
Get `http://host/light/mode/195`
After a delay the lights in the pool/spa are set to red as expected
Get `http://host/circuit`
The state changes from the first get are never reflected.

Using pool-controller 5.2.0

**Comment by tagyoureit** [comment]
Included with 5.3.0 released today.
