### ISSUE TITLE
Update API notes for Intellibrite calls

### ISSUE THREAD

**Issue by rerouted** [tagyoureit/nodejs-poolController#126]
Just a issue reminder to update the README.md with the Intellibrite API calls.

* setLightMode(mode)
* setLightColor(circuit, color)
* setLightSwimDelay(circuit, delay)
* setLightPosition(circuit, position)

**Comment by tagyoureit** [comment]
LightGroup data structures are documented [here](https://github.com/tagyoureit/nodejs-poolController/wiki/Version-6-Data-Structures#7-light-group).  Intellibrite is now always LightGroup[0] (with id:192) on *Touch systems.  

All available options can be retrieved from `http://localhost:4200/config/options/lightGroups`.
LightGroup variables can be updated with a PUT to `http://localhost:4200/config/lightGroup`.

We'll continue to work on the documentation but HTH.

**Comment by tagyoureit** [comment]
Updated in new API documentation: https://tagyoureit.github.io/nodejs-poolcontroller-api/
