### ISSUE TITLE
api call to toggleCircuit(equipment) with invalid equipment throws error in 6.0-DEV

### ISSUE THREAD

**Issue by emes** [tagyoureit/nodejs-poolController#128]
### Expected behavior and actual behavior

bad request should be ignored or get a non-fatal error.

socket.io call to toggleCircuit('moo') results in following error.

### What is actually happening (screenshots are helpful)

```
15:43:15.000 verbose: Msg# 323: 

TypeError: Cannot read property 'status' of undefined
    at Object.toggleCircuit (/src/lib/equipment/circuit.ts:734:61)
    at Socket.<anonymous> (/src/lib/comms/socketio-helper.ts:249:21)
    at Socket.emit (events.js:189:13)
    at /app/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
nodejs-poolController has closed successfully.
```
### Steps to reproduce the problem

toggleCircuit('moo')

**Comment by tagyoureit** [comment]
moo?  The program should crash on that!  I put in some validation here.  I need to do this on all inputs but that will take quite a while.
