### ISSUE TITLE
Pump only - don't have intellitouch or intellicomm

### ISSUE THREAD

**Issue by rsandoz** [tagyoureit/nodejs-poolController#130]
Is it possible to use this with the pump only and no intellitouch or intellicomm controller?

I have the pump only and I bought a USB RS485 adapter an plan to hook it to the directly pump.

(Pentair IntelliFlo VS Plus SVRS Variable Speed in Ground Pool Pump - 011057)

I am using version 5.3.0
I set equipment as follows:
    "equipment": {
        "controller": {
            "intellicom": {
                "installed": 0,
                "friendlyName": ""
            },
            "intellitouch": {
                "installed": 0,
                "friendlyName": "",
                "numberOfCircuits": 20,
                "numberOfPumps": 1,
                "numberOfCustomNames": 10,
                "numberOfSchedules": 12
            },
            "virtual": {
                "pumpController": "default",
                "chlorinatorController": "default"
            }
        },
Console shows:
DEBUG LOG ... 
09:13:25.277 INFO No pool controller (Intellitouch or IntelliComII) detected. No configuration request messages sent.
09:13:43.212 WARN queuePacket: Not queueing packet 165,0,96,33,4,1,255 because SerialPort/Net connect is not open.
09:13:43.217 WARN queuePacket: Not queueing packet 165,0,96,33,7,0 because SerialPort/Net connect is not open.
09:14:08.945 ERROR Error opening port: Opening /dev/ttyUSB0: Unknown error code 3. Will retry in 10 seconds

**Comment by tagyoureit** [comment]
If you have the pumps section set to have 1+ [pump](https://github.com/tagyoureit/nodejs-poolcontroller#pump) it should start the virtual controller automatically.  You can also set the virtual [pumpController](https://github.com/tagyoureit/nodejs-poolcontroller#virtual) to `always`.  

I would expect the debug log entries that you are seeing until you plug in the adapter.  When you get your adapter check the [wiki](https://github.com/tagyoureit/nodejs-poolController/wiki/RS-485-Adapter-Details).

**Comment by tagyoureit** [comment]
Closing this.  If you still have issues please re-open.
