### ISSUE TITLE
adjust temp ranges in UI based on C/F

### ISSUE THREAD

**Issue by emes** [tagyoureit/nodejs-poolController#135]
Just for the UI...

set temperature ranges are 50-110 which is great for most people.

check UOM to see if Celsius and make low/high 15-45

**Comment by tagyoureit** [comment]
Can you check this?  Pushed to 6.0.

![2019-06-03_11-36-43](https://user-images.githubusercontent.com/1646840/58826113-cbd8ac80-85f4-11e9-8882-f45f0550791e.jpeg)

**Comment by emes** [comment]
Looks great!  Thanks for digging in!

<img width="508" alt="image" src="https://user-images.githubusercontent.com/363010/58840138-889d2e80-8632-11e9-82ff-5e0f8d3e2d44.png">
