### ISSUE TITLE
Expose version from http API

### ISSUE THREAD

**Issue by leftyfl1p** [tagyoureit/nodejs-poolController#139]
Currently there is no way to retrieve the poolcontroller version from the http API. This is useful (and in my opinion necessary) for extensions to check against for version compatibility reasons. Especially with the upcoming 6.0 which may or may not include breaking changes this should be included in some non breaking 5.x update.

**Comment by dhop90** [comment]
Have you tried http://<pool controller ip>:3000/device?

it should return an xml structure with the version with major and min numbers

**Comment by leftyfl1p** [comment]
Interesting that @tagyoureit didn't mention this to me when I asked him about it although this is in xml and I would prefer to have it in json rather than using another parsing library just for 1 endpoint.

**Comment by dhop90** [comment]
This is all the processing I needed:
 def msg = hubResponse.xml
    if (msg) {
      def body = msg
        if (!body) {
            logerror "body was nil, returning"
            return null
        }    
        def verMajor = body.specVersion.major
        def verMinor = body.specVersion.minor
        def verPatch = body.specVersion.patch
        def manufacturer = body.device.manufacturer
        def modelDescription = body.device.modelDescription
        def friendlyName = body.device.friendlyName

**Comment by tagyoureit** [comment]
This is included with the `/config/all` endpoint in 6.0.
