### ISSUE TITLE
Wiring RS485 Directly to Intelliflo

### ISSUE THREAD

**Issue by Exit2Studios** [tagyoureit/nodejs-poolController#140]
I apologize if I've missed something obvious, but I've searched and unable to find the information.  How do I physically connect the RS485 adapter to my VSF pump?  Also, if there are any tutorials out there for newbies, I would appreciate it.

### Expected behavior and actual behavior
Trying to connect JBTek adapter to stand-alone pump

### What is actually happening (screenshots are helpful)
Unable to find instructions on how/where to physically wire the serial connector

### Specifications

1. What version of the code are you using? 5.3.1
2. All output from the file log (See [packet capture](https://githu.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution)) - NA
3. Any errors that are in the console - NA
4. Your config.json or in-use configuration file - NA
5. Your pool equipment _Pentair Intelliflo VSF

**Comment by tagyoureit** [comment]
You need a [cable](https://www.amazon.com/Pentair-350122-Communication-Plumbing-50-Feet/dp/B0087N4TUY/ref=asc_df_B0087N4TUY/?tag=hyprod-20&linkCode=df0&hvadid=198100862572&hvpos=1o1&hvnetw=g&hvrand=2143392514254812725&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1013964&hvtargid=pla-321250928838&psc=1) from Pentair to connect into the pump.
