### ISSUE TITLE
Cannot install, (Serial port fails to install)

### ISSUE THREAD

**Issue by LavaGlass** [tagyoureit/nodejs-poolController#147]
Expected Behavior: Running "npm install" in the nodejs-poolcontroller directory would install all dependencies, etc.

Actual Behavior: Errors occur saying that serialport could not be installed and that it cannot write to a certain directory.

![image](https://user-images.githubusercontent.com/30231703/69767096-9b9c5000-11ca-11ea-9cba-e71d631dc370.png)

Steps to reproduce the problem: Run npm install.

1. What version of the code are you using?
5.2.0 (tried with 5.3.0 aswell)

3. Any errors that are in the console
Lots! See Here: https://pastebin.com/CF7K767n

4. Your config.json or in-use configuration file
N/A

5. Your pool equipment
N/A

Any help is appreciated as I have been searching on the serialport docs, issues here and even followed the steps in this issue to no avail. https://github.com/tagyoureit/nodejs-poolController/issues/113

Thanks.

**Comment by tagyoureit** [comment]
Looks like those serialport docs got moved [here](https://serialport.io/docs/guide-installation).

99% of the time the command `sudo npm install serialport --unsafe-perm --build-from-source` resolves the issue.

I would also recommend dropping back to Node v8 (maybe v10).  Looks like you are on v12 which might not be supported by the version of serialport packaged with 5.2/5.3 of this app.  You could also try to upgrade the serialport dependency but usually running the latest Node version creates some kind of havoc.

**Comment by LavaGlass** [comment]
FIXED!

Downgraded to Node 8.9 and it works like a charm.

Thanks @tagyoureit 

![image](https://user-images.githubusercontent.com/30231703/69778434-39584500-11f4-11ea-994c-d96684310534.png)
