### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by dwijnker** [tagyoureit/nodejs-poolController#149]
Apologies if this is not the best way to do this, but I'm currently running version 5.3.0 on a Raspberry Pi Zero W connected to my Easytouch 8 and I couldn't be happier. I wanted to say to all a heartfelt **Thank You!** to all who have contributed. Please keep up the great work, I hope to be a part of it someday as well.

**Comment by tagyoureit** [comment]
Really appreciate the comments!  Thanks.
