### ISSUE TITLE
Support for Jandy JXI heaters under Virtual Controller

### ISSUE THREAD

**Issue by timelery** [tagyoureit/nodejs-poolController#151]
Do you have any experience interfacing with the Jandy JXI heaters over iAqualink protocol? I was hoping to add support under the virtual controller interface. Anything related to the message format or similar would be very helpful.

**Comment by tagyoureit** [comment]
Most of the heaters are based on a fireman's kill switch.  I haven't looked into (nor do I have) a heater like that to test.  Best way is to put a middleman and see what is being sent over the wire to the heater.  Let me know if you find anything but not sure I'll be much help otherwise.
