### ISSUE TITLE
Constant timeouts on serial port under 6.0

### ISSUE THREAD

**Issue by timelery** [tagyoureit/nodejs-poolController#154]
@tagyoureit Any ideas on this one? Connected directly to Intelliflo pump on ttyUSB0 under 6.0 branch.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/1464479/77126242-bad31d80-6a05-11ea-9504-fe8b09287da5.png">

**Comment by tagyoureit** [comment]
There is a setting in `config.json` which is `"inactivityRetry": 10`.  This will reset the port after 10s.  If you are manually controlling the pumps, then you won't have any packets and it will reset often.  Just set this really high and it won't reset the port automatically.
