### ISSUE TITLE
Not capturing all Easytouch2 4p (virtual) circuits

### ISSUE THREAD

**Issue by baudfather** [tagyoureit/nodejs-poolController#159]
### Expected behavior and actual behavior
Expected to load all circuits in v6, in my example circuits 11 and 12.  V6 only loads the first 4 circuits

### What is actually happening (screenshots are helpful)
Unable to access circuts above 4

### Specifications

1. What version of the code are you using? 
6.0, attached packet capture from 5.3

2. All output from the file log 
[packetCapture1.zip](https://github.com/tagyoureit/nodejs-poolController/files/4525594/packetCapture1.zip)

3. Any errors that are in the console
No errors.

4. Your config.json or in-use configuration file
from v6: [config.zip](https://github.com/tagyoureit/nodejs-poolController/files/4525600/config.zip)

5. Your pool equipment 
Pentair Easytouch 4p w/ intelliflo VSF pump

**Comment by tagyoureit** [comment]
Can you pull the `next` code I just pushed up now?  You may need to delete your `poolConfig.json` and `poolState.json` to pick up the new changes.

**Comment by baudfather** [comment]
Success!

**Comment by tagyoureit** [comment]
Ok, great!  Closing for now.
