### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by arrmo** [tagyoureit/nodejs-poolController#16]
Thoughts? Would this make sense?

iPhone too ... but I don't have one of those to test with / develop on ... :-(.

**Comment by tagyoureit** [comment]
Yeah, would love to... but I don't know much about programming iOS or Android at the moment.  Likely need to get help with this one.

**Comment by rmonty** [comment]
I have written an Android app that work with IntelliCenter if you want to give it a go.  See this thread for more info...
 https://www.troublefreepool.com/threads/intellicenter-gateway-and-control-apps.214299/

**Comment by tagyoureit** [comment]
Very cool... thanks for the note.  Great threads on TFP, as well.

**Comment by tagyoureit** [comment]
Closing due to lack of ownership.
