### ISSUE TITLE
FEATURE REQUEST: Chlorinator dosing indicator

### ISSUE THREAD

**Issue by johnny2678** [tagyoureit/nodejs-poolController#164]
### Expected behavior and actual behavior
Right now, on my Pentair IC40, there's a light that indicates whether the unit is dosing.  If the SWG is set to 100%, the light is always on.  If SWG is set to 50%, it's on half the time, off the rest.  

I modulate my dosing throughout the day based on ORP levels so I'd like a way to track the amount of time the unit spends dosing.

If we can pull the status, then I can use python/influx functions to achieve.

This is a NEXT 6.x feature request.

![IMG_3569](https://user-images.githubusercontent.com/8219743/82132226-7668c180-97ab-11ea-8ee4-7b9c127b58c3.jpg)

**Comment by tagyoureit** [comment]
Hi @johnny2678, I finally had a chance to look at this.  I watched the light go on/off as it was generating (or not) chlorine but the messages didn't change at all.  Maybe I'm missing something but I think the only was to capture this might be to put a voltage or current sensor on the physical lines.  

Happy to include this if we learn differently but just don't think it's possible now.
