### ISSUE TITLE
Config.json resets with malformed file

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#166]
If the JSON isn't correct in the `config.json` it blows it away and configures it anew from the `defaultConfig.json`.  

This isn't ideal as there could be many customized settings in there and the user isn't notified of the error nor the change.

I think I'd prefer to have the app abort than overwrite, but the broader question would be how to add new keys or change keys if the defaultConfig changes.  I previously [solved this](https://github.com/tagyoureit/nodejs-poolController/blob/master/src/etc/settings.js#L335) in v5.3 but maybe there is a better approach?

**Comment by rstrouse** [comment]
I added code to abort the process when the config.json is malformed.  Keys from the default still get applied only on success.
