### ISSUE TITLE
Cannot find module 'jszip'

### ISSUE THREAD

**Issue by jarrah42** [tagyoureit/nodejs-poolController#170]
I started logging using the webClient, however when I stop the logging, the following error is generated:

1|poolController            | 192.168.1.112 GET /app/config/stopReplay {}
1|poolController            | error: Cannot find module 'jszip'
1|poolController            | Require stack:
1|poolController            | - /home/pi/nodejs-poolController/dist/logger/Logger.js
1|poolController            | - /home/pi/nodejs-poolController/dist/app.js

**Comment by tagyoureit** [comment]
Please re-run `npm i` on the app.  Node doesn't have built-in zip functionality and JSZip is a new dependency that was added to the app.
