### ISSUE TITLE
6.0 name

### ISSUE THREAD

**Issue by rsnodgrass** [tagyoureit/nodejs-poolController#177]
The existing name of nodejs-poolController is long to continually spell out...and the fact it is built on nodejs really isn't relevant to its purpose from a user perspective.  Have you thought about changing the product name to be more concise as part of the 6.0 release?

Some ideas:

Next Pool Controller
Next Pool Hub
OctoPOOL Hub - intelligent tentacles to pool and home automation
PoolIO - Pool I/O
PoolBrain
PoolBroker

**Comment by tagyoureit** [comment]
We'll take it under consideration, thanks.  :)
