### ISSUE TITLE
Freeze Protection

### ISSUE THREAD

**Issue by arrmo** [tagyoureit/nodejs-poolController#18]
Not working right on my Intellitouch ... :-(.

**Comment by arrmo** [comment]
FYI, 
![image](https://cloud.githubusercontent.com/assets/8756384/22372810/6f8d78cc-e464-11e6-97e6-18b1794eac5b.png)

**Comment by tagyoureit** [comment]
Yup, I haven't push it yet.  It will be in with the next push.  If you want to test it on your end, change the end of line 40 in `lib/comm/inbound/controller/2.js` to `(data[c.controllerStatusPacketFields.UOM] & 8) >> 3`.

**Comment by arrmo** [comment]
NP, will wait for the push - then test it here (supposed to be cold again tomorrow morning ... :-().

**Comment by tagyoureit** [comment]
I think we are good on this.  Let me know if we need to reopen.

**Comment by arrmo** [comment]
Will do - 81F here today, no freeze protection on ... LOL
