### ISSUE TITLE
Does this Project work with Handy VSP Pumps?

### ISSUE THREAD

**Issue by lfiocco** [tagyoureit/nodejs-poolController#180]
Hello and Sorry I just discovered this project. Does the VS code work with Jandy ProFlo VSP pumps? I also have a IQPump01 that talks to it.

**Comment by tagyoureit** [comment]
Unfortunately, I don’t know. You will just have to try it.

**Comment by tagyoureit** [comment]
I just came across An answer on Amazon that seems to indicate “no”. But since it is RS-485 it could be decoded.
