### ISSUE TITLE
Does not see Aquarite

### ISSUE THREAD

**Issue by katodude** [tagyoureit/nodejs-poolController#185]
Have the pi connected directly to the Aquarite. Have separate 12v power and ground applied to the Aquarite. Tried two different RS-485 adaptors, and have reversed the wires. 
[replay (9).zip](https://github.com/tagyoureit/nodejs-poolController/files/4878950/replay.9.zip)

**Comment by tagyoureit** [comment]
Interesting... the Aquarite was responding with message 22 which I've only (recently) seen coming from the iChlor.  However, the iChlor was reporting the temperature and I didn't see that on yours.  Maybe the pumps weren't running?  Couldn't tell from the packet capture.  Do let me know if you get the temperature as I may ask you for another packet capture at that point.

Pull the latest.
