### ISSUE TITLE
Virtual Pump Controller - Intelliflow VS

### ISSUE THREAD

**Issue by raymop** [tagyoureit/nodejs-poolController#188]
[replay-2.zip](https://github.com/tagyoureit/nodejs-poolController/files/4906810/replay-2.zip)
### Specifications

1. What version of the code are you using?
2. All output from the file log (See [packet capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution))
3. Any errors that are in the console
4. Your config.json or in-use configuration file
5. Your pool equipment

**Comment by tagyoureit** [comment]
As mentioned in Gitter, you are running a very old version of the code.  Please download the latest or run `git clone` (depending on how you grabbed the code initially).  You need to do this for both the main app and any clients you are running.
