### ISSUE TITLE
Please update README with instructions to control njspc with systemd

### ISSUE THREAD

**Issue by dkossman** [tagyoureit/nodejs-poolController#191]
This systemd setup worked for me on Raspbian - can you add to the README?  Seems like it might be helpful for others.  This is based on a gitter post by @guru-florida, slightly adjusted for my configuration.

`pi> sudu vi /etc/systemd/system/poolController.service  # or your favorite editor`

this file should contain the following. You may need to edit to adjust the user, working directory, or start command for your installation and OS:
```
[Unit]
Description=NodeJS Pool Controller
Documentation=https://github.com/tagyoureit/nodejs-poolController/
After=network.target

[Service]
Environment=NODE_ENV=production
Type=simple
User=pi
WorkingDirectory=/home/pi/nodejs-poolController
ExecStart=/usr/local/bin/node dist/app.js
Restart=on-failure
RestartSec=15s

[Install]
WantedBy=multi-user.target
```
Then run these commands:

```
pi> sudo systemctl daemon-reload
pi> sudo systemctl enable poolController
pi> sudo systemctl start poolController
```
To check the status of the service:
`pi> systemctl status poolController  `

To tail the log:
`pi> sudo -n journalctl -o cat -n 2500 -f -u poolController  # tail the poolController log, -u option is based on service name`

To stop, restart or disable the service, use the appropriate systemctl command:
```
pi> sudo systemctl stop poolController
pi> sudo systemctl restart poolController
pi> sudo systemctl disable poolController
```

**Comment by tagyoureit** [comment]
Added this to the [wiki](https://github.com/tagyoureit/nodejs-poolController/wiki/Automatically-start-at-boot---PM2-&-Systemd) and added to Readme!  Thanks very much.
