### ISSUE TITLE
How to use RS485 adator with Pentair "3 wire" system?

### ISSUE THREAD

**Issue by flashvenom** [tagyoureit/nodejs-poolController#198]
I'm finally at the last leg of my project - hooking up my Pentair heater to my raspberry pi using a serial connection. I'm just not sure WHERE to hook up the wires using the USB RS485 serial connection so that I can utilize this library... I'm controlling everything else (pumps/lights/actuators) with my own code. But I can't for the life of me figure this part of it out. My pentair heater is a three wire system (model 472592) but my RS485 serial USB adapter is two wires. And then I don't see how this connection could even set the temps. Or maybe I'm just totally not understanding how this works. This part of the project I haven't been able to find many resources. Any feedback would be appreciated!
The manual: https://imgur.com/a/327lOFp
The serial connector: https://imgur.com/a/MeiVRXW

**Comment by tagyoureit** [comment]
The heater is controlled via a fireman's switch.  It isn't RS485.  If the circuit completes the "pool" setting it will run the heater at the pool temp; likewise for spa.  No way to control it programmatically.  The best you can do is add in a 24v 0.5a relay that you trigger via code.
