### ISSUE TITLE
Heat state not accurate when using manual spa heat with EasyTouch

### ISSUE THREAD

**Issue by gadget-monk** [tagyoureit/nodejs-poolController#200]
**Describe the bug**
poolController heater status is not accurate when heat mode is set to Off and Manual Heat is enabled on EasyTouch systems. 

**To Reproduce**
1. Go to web client, ensure Heat mode is set to off. In EasyTouch settings enable Manual Heat.
2. Click on 'Spa' button to enable Spa body. Pump and heater turns on. 
3. Scroll down to 'Heat' status in webclient
4. See error - heater status is off (no flame)

**Expected behavior**
Heater status is webclient is consistent with actual heater status. Heater status is accurate in web client when heat mode is auto and heater comes on. 

**Screenshots**
None

**Packet Capture**
Attached

**Pool Equipment**
 - Controller: EasyTouch
 - Controller Model:  EasyTouch2 8
 - Controller Firmware Version: ?
 - Pump(s) manufacturer and model: Intellipro VF
 - Chlorinator: None
 - Heater(s): gas
 - Chemical controller: None
 - Valves: None
 - Any other relevant equipment: None

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[replay-heater.zip](https://github.com/tagyoureit/nodejs-poolController/files/5004994/replay-heater.zip)

**Comment by rstrouse** [comment]
@tagyoureit I sent you an e-mail regarding heatStatus and heatMode.  This is the replay that I was reviewing at around message id 36201 it starts broadcasting the heatStatus.  Btw, I fixed an issue in messageManager for the response objects this morning.

**Comment by tagyoureit** [comment]
Pull the `next` branch and try now.  Replay looks accurate.

**Comment by gadget-monk** [comment]
hi, I ran the update, haven't had a chance to test with heater on yet but noticed two issues: 
a. in web client, "either heater" virtual circuit is On even when heater is off (Spa heater and Pool heater virtual circuits are off
b. my homebridge client is broken because the body emit no longer includes HeatStatus

**Comment by tagyoureit** [comment]
I just pushed up a quick fix.  I excluded the heatStatus when the tbody was off.  I'm seeing the heatStatus in the emit now.  I'm not seeing "either heater" on, however.  That should be complemented by "pool heater" or "spa heater".  Pull the latest and let me know if that fixes it.

**Comment by gadget-monk** [comment]
everything works perfectly, heatStatus is working as it used to earlier (i.e. it is included even if body is off). thanks!
