### ISSUE TITLE
v6 API Docs?

### ISSUE THREAD

**Issue by jbarneson** [tagyoureit/nodejs-poolController#204]
is there v6 API documentation available? i have easily configured and been able to retrieve information from my pentair system, but I want to be able to post pump updates, or chlorine levels, or heater changes as well..

**Comment by tagyoureit** [comment]
https://tagyoureit.github.io/nodejs-poolcontroller-api/.

This may be combined with this repo at some point, but it's under a separate one for now.  It's also brand new so any/all feedback is welcome.
