### ISSUE TITLE
Change button layout for mobile devices

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#21]
The buttons are really small on mobile devices.  One suggestion would be to just make them bigger.  Another would be to eliminate the labels and place them on the buttons themselves.  We could then dual-column the panel, like in the attached pic.

<img width="499" alt="screen shot 2017-02-11 at 10 08 36 am" src="https://cloud.githubusercontent.com/assets/1646840/22856213/3b614f62-f042-11e6-976b-d2303ffc9aac.png">

Of course, adding some space between the buttons... but I think this just means adding a couple of extra classes (eg `<div class="col-xs-6 col-md-6">`).  I used DIV's to mark this up, bit might work withy our existing table layout as well.

**Comment by arrmo** [comment]
Thinking about this - not quite sure yet what to do about it. I'm not sure just making everything a button works, and to be honest then it gets a bit messy on a PC, and is also difficult to follow. We could change themes ... less white space, larger font, etc.

Thoughts?

**Comment by tagyoureit** [comment]
The bootstrap code allows for responsive layouts,right?  So in theory we should be able to keep the layout we have now for PC/big screen, and add code so that when the screen is more narrow it changes to the more button-like layout.  Have you played with that at all?

**Comment by arrmo** [comment]
Check out PR #33, Pool (only) ... better? I can fix this throughout if it's better.

**Comment by tagyoureit** [comment]
Ya, on iPhone it is much better.  On iPad it is also better, but we need to adjust one of the widths because the buttons wrap.  See pics.

![img_0027](https://cloud.githubusercontent.com/assets/1646840/23335837/8b2641c0-fb72-11e6-8133-992d092e1027.PNG)
![img_0860 2](https://cloud.githubusercontent.com/assets/1646840/23335838/8db538d8-fb72-11e6-8b19-e662788c3463.PNG)

**Comment by arrmo** [comment]
Yep, agreed. So make them all larger like this, and fix the wrapping - good with you?

**Comment by tagyoureit** [comment]
Yup.  👍

**Comment by arrmo** [comment]
Perfect - will take care of it. I also want the Parameter (on the left) centered vertically - need to figure that out. I know, minor, but I'm fussy about that ... :)

**Comment by arrmo** [comment]
Addressed - buttons updated, alignment (css) fixed, and wrapping as well (also css). Will close, reopen if needed.

BTW, this is PR #36.
