### ISSUE TITLE
Add virtualCircuits to mqtt.json

### ISSUE THREAD

**Issue by Botched1** [tagyoureit/nodejs-poolController#217]
virtualCircuits currently do not make it to MQTT.

Consider adding this (or something like it, maybe with an enabled property?) to the mqtt.json file. I tested this on my 6.1.1 install, and it worked as expected.

        {
            "name": "virtualCircuit",
            "description": "Populate the virtual circuits topics",
            "topics": [
                {
                    "topic": "state/virtualcircuits/@bind=data.id;/@bind=data.name;",
                    "message": "{\"id\":@bind=data.id;,\"isOn\":@bind=data.isOn?'\"on\"':'\"off\"';}",
                    "description": "Bind 'on'/'off' as a message to the state topic."
                }
            ]
        },

results:
![image](https://user-images.githubusercontent.com/19985320/94162091-f682f000-fe4b-11ea-9996-8bd2f77151de.png)

**Comment by tagyoureit** [comment]
Added!  Thanks.
