### ISSUE TITLE
Easytouch Lite EZPL4 P/N 522523 shows as "Unknown OCP[7,13]

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#219]
Connect a Easytouch Lite EZPL4 board P/N 522523, 
In Dash panel, select "Reload Config" on "Systems" tab of Settings, and the 
board shows as "Unknown OCP[7,13]

**Comment by tagyoureit** [comment]
This is the first one we've seen.  The PSL4 is 6,13 and I had guessed that this was 5,13.  Now updated to 7,13.  You'll want to pull the `next` branch until I merge this back with `master`.  Thx.
