### ISSUE TITLE
Schedule shows a duplicate of the only one schedule

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#221]
Duplicate of the one schedule event.
![Poolcontroller 9-28](https://user-images.githubusercontent.com/8471168/94470932-55bb6a00-0196-11eb-8fe4-82d35d76f727.JPG)

**Comment by miamijerry** [comment]
Resolved by replacing SD card image from before connection with 522523 Easytouch Lite PL4 board

**Comment by tagyoureit** [comment]
If you switch between systems you should remove the data/*.json files.  That's likely what the older SD card image is doing but we store everything in these config files.

**Comment by miamijerry** [comment]
OK, 
Then I then delete these files;
data/*.json files
when switching between systems...
