### ISSUE TITLE
How to edit an existing scheduled event?

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#225]
How do I edit a previously scheduled event? 

IE pool runs from 10:00am to 6:00pm, and I want to change the start time...

When I go to the schedule tab in settings, I only see a box to add a new schedule event.

Second question how do I delete a scheduled event?

(note - I have a Autelis pool control also)

**Comment by tagyoureit** [comment]
This is an in-progress item in webClient.  @rstrouse has this implemented in dashPanel.  I should have this available in webclient in the next couple of weeks but super slammed right now.

**Comment by miamijerry** [comment]
Thank you for all your hard work.

**Comment by tagyoureit** [comment]
I just pushed up the code for this.  Pull the `next` branch of both njsPC and webClient.
