### ISSUE TITLE
Newly created schedules do not display properly until after a reload happens

### ISSUE THREAD

**Issue by george-basco** [tagyoureit/nodejs-poolController#226]
A new schedule created via ``PUT /config/schedule``:
https://github.com/tagyoureit/nodejs-poolController/blob/8d1b9e19b5abc6c9204ac05f8eea4746125f3f07/controller/boards/IntelliCenterBoard.ts#L2780

does not have its ``isActive`` flag set and therefore does not get displayed properly until after a reload is done.

**Comment by rstrouse** [comment]
Added the isActive flag on save.

**Comment by george-basco** [comment]
Thanks, works now.

**Comment by rstrouse** [comment]
Awesome <- Gonna run out of exclamations
