### ISSUE TITLE
PH and ORB valves to not update without reloading page - DashPanel

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#228]
Intelichem readings for PH and ORB do not update in dashPanel without a page reload. 

They do update in webClient without a page reload.

**Comment by rstrouse** [comment]
I'll have a look.  Are you referring to the setpoints or the levels.  I do not have an IntelliChem so it is kinda difficult to test beyond mocking it up.  Btw did you used to have a Vera home automation system with Autelis?

**Comment by rstrouse** [comment]
Pull a new dashPanel.  I think I may have found the issue.

**Comment by miamijerry** [comment]
Yes, I have the Autelis unit also, I moved it from Vera to Homeseer.
![Chemistry](https://user-images.githubusercontent.com/8471168/95001777-2ee8a380-059b-11eb-96a5-e789a8b5b75b.JPG)
The 7.1 and 685 numbers are what I was referring to.

**Comment by rstrouse** [comment]
The death of Autelis led me here.  I wrote the Autelis integration with Vera and seemed to remember your id.  I also wrote an integration with njspc to Vera as well.

Did you pull an new dashPanel?

**Comment by miamijerry** [comment]
I asked you to write an integration of njspc to Homeseer recently.
(I have one dead, and two living Autelis units)

Pulled a new dashPanel, and the problem still persists

**Comment by rstrouse** [comment]
Just to be sure.  Hard refresh your browser.  I can’t seem to figure out how to not cache scripts in nodejs.

**Comment by miamijerry** [comment]
Just realized that I did not reboot the RPI after the dashPanel pull.

![Error](https://user-images.githubusercontent.com/8471168/95009068-09848580-05ed-11eb-92c0-c4c7936c39d8.JPG)

Now there is no connection. shows "unknown model".
messageManager shows "ready" in top right corner.
webClient is working...

**Comment by miamijerry** [comment]
Contains of themes folder

![Themes folder](https://user-images.githubusercontent.com/8471168/95009234-67659d00-05ee-11eb-967d-18d2d16f5464.JPG)

**Comment by miamijerry** [comment]
This got a working copy up

![reset1_result](https://user-images.githubusercontent.com/8471168/95010018-3daf7480-05f4-11eb-9c82-b0026c47e761.JPG)

**Comment by miamijerry** [comment]
OK, I find it working this morning.

Hope all this makes sense to someone.
