### ISSUE TITLE
Creating a circuit group that has a circuit with an undefined desiredState fails

### ISSUE THREAD

**Issue by george-basco** [tagyoureit/nodejs-poolController#230]
If you create a new circuit group and leave a circuit with an undefined desiredState, the operation fails.

dashPanel does report an error, although doesn't give a reason why.  BIgger problem is that njsPC stores this as a circuit group, so doing things with it can cause weird behavior.

Seems like both njsPC and dashPanel should default circuits to "on" if a desiredState is not given.

**Comment by rstrouse** [comment]
I agree and will make the change.

**Comment by rstrouse** [comment]
I made the change pull njspc and dashPanel.

**Comment by rstrouse** [comment]
Closing this after setting default desiredState values.
