### ISSUE TITLE
IC-40 Chemistry Section Missing 

### ISSUE THREAD

**Issue by tamu20** [tagyoureit/nodejs-poolController#232]
**Describe the bug**
Dashpanel Chemistry section is not displayed & MQTT is not reporting salt level.  poolState and API list the salt level

**To Reproduce**
1. Go to dashpanel on port 5150

**Expected behavior**
Chemistry section to be displayed and MQTT report salt level

**Screenshots**
N/A

**Packet Capture**
[2020-10-12_19-14-03.zip](https://github.com/tagyoureit/nodejs-poolController/files/5372000/2020-10-12_19-14-03.zip)

**Pool Equipment**
 - Controller: IntelliCenter
 - Controller Model: IntelliCenter i5PS
 - Controller Firmware Version: 1.047
 - Pump(s) manufacturer and model: Intelliflow VSF

 - Chlorinator: IntelliChlor-40
 - Heater(s): gas
 - Chemical controller: N/A
 - Valves: Intellivalve
 - Any other relevant equipment:

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser chrome

**Comment by tagyoureit** [comment]
MQTT bindings are [here](https://github.com/tagyoureit/nodejs-poolController/blob/master/web/bindings/mqtt.json#L161).

**Comment by rstrouse** [comment]
I added salt level to the mqtt.json bindings.  I followed the existing format.
