### ISSUE TITLE
Minimum Nodejs / NPM needed...

### ISSUE THREAD

**Issue by MYeager1967** [tagyoureit/nodejs-poolController#238]
Will this run on an original RPi? What are the minimum versions of Nodejs and NPM?

**Comment by rstrouse** [comment]
You need node version 10+.  I don’t know what versions are supported by pi model.

**Comment by MYeager1967** [comment]
I actually managed to get v12 on the old beast. Now I either need to find my RS-485 dongle or get another one... Does it provide a web page that can be accessed or does it require a special client?

**Comment by rstrouse** [comment]
It requires a client either -webClient or -dashPanel or no client at all if you are accessing it via some other means.  The first two are listed in the Wiki and the last one you don't even need to install. ;-)
