### ISSUE TITLE
Standalone Virtual Controller: Set temperatures via MQTT topic. 

### ISSUE THREAD

**Issue by orrious** [tagyoureit/nodejs-poolController#239]
Currently temperatures are able to be set externally via REST API:
```PUT /state/temps { waterSensor[1-4]: number, solarSensor[1-4], airSensor1: number }```

There is also a calibration offset API as well through general but this may only work with IC as I don't know how touch handles it.

Please provide MQTT topic to set the same values as in REST API.  I would request that you accept any float/decimal value via MQTT and either perform a round or just drop anything after the decimal. Most sensors put out 2 decimal places for temperature. It would be a shame to have to write something externally just to round/drop the decimal

**Comment by rstrouse** [comment]
I added the endpoints for this to the MQTT interface.  For the calibration there is a ```/config/tempSensors { waterTempAdj[1-4]: <+-degrees>, solarTempAdj[1-4]: <+- degrees>, airTempAdj:<+- degrees>}``` and the corresponding command topic.  Unfortunately, the calibration can't really do anything until we create a board object for an all out virtual controller.
