### ISSUE TITLE
RS485 needed for Intellicenter?

### ISSUE THREAD

**Issue by macjeff** [tagyoureit/nodejs-poolController#241]
Since Intellicenter data is cloud based why do you need a connector?  Cant you just log in and retrieve the data?

**Comment by rstrouse** [comment]
You can't really just log in and retrieve the data.  There is no published API for either potential interface.  However, one of the primary goals of this was to not be reliant on equipment not residing within the local network and support equipment other than just IntelliCenter.  There is a guy out on TFP that has tapped into the gateway for IntelliCenter though.
