### ISSUE TITLE
Where is lat / long suppose to be entered?

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#245]
Seeing this flooding poolController terminal;

[11/2/2020, 10:19:21 AM] warn: dt:Mon Nov 02 2020 09:59:20 GMT-0500 (Eastern Standard Time) lat:undefined lon:undefined Not enough information to calculate Heliotrope.

Entering address did not resolve...

**Comment by tagyoureit** [comment]
It's not by address, it's latitude and longitude.  Address is just for the "pool owner" information but sunrise/sunset are calculated locally via lat/long so we don't need to make any calls out to the internet to interpolate the address.

**Comment by miamijerry** [comment]
The question is "Where do I enter Lat / Long ??"

**Comment by rstrouse** [comment]
Close njspc then edit the poolConfig.json file in the data directory.  You want to enter the latitude and longitude in the pool.location node.  Then restart njspc.
```"pool": {
    "options": {
      "clockMode": 12,
      "clockSource": "internet",
      "units": 0,
      "adjustDST": true,
      "pumpDelay": false,
      "cooldownDelay": false,
      "manualPriority": false,
      "manualHeat": false
    },
    "alias": "Pool",
    "owner": {
      "name": "Mr. President",
      "phone": "5555555555",
      "phone2": "",
      "email": "",
      "email2": "mail2@home.com"
    },
    "location": {
      "zip": "20500",
      "latitude": 38.89,
      "address": "1600 Pennsylvania Avenue NW",
      "longitude": -77.036,
      "timeZone": 131,
      "country": "United States",
      "city": "Washington",
      "state": "DC"
    }
```
In the future I will add this to dashPanel so you can add it from there.

**Comment by tagyoureit** [comment]
How did you enter the address?  The lat/long is right below that.

![2020-11-02_08-09-35](https://user-images.githubusercontent.com/1646840/97929943-37113b80-1d1f-11eb-8b4f-031f59fcf78d.png)

![2020-11-02_08-09-56](https://user-images.githubusercontent.com/1646840/97929963-42fcfd80-1d1f-11eb-8e98-299152ba902a.png)

**Comment by tagyoureit** [comment]
This also works in Dashpanel now.

![2021-01-07_20-28-19](https://user-images.githubusercontent.com/1646840/103974827-78f79d00-5127-11eb-8951-00f9146fa2d2.png)

**Comment by miamijerry** [comment]
Thank you

**Comment by gambler2841** [comment]
I apologize in advance, I'm not extremely experienced with Linux or the Raspberry Pi. I'm encountering a problem with connecting to the pool controller. I am getting hung up on the following:

![Capture](https://user-images.githubusercontent.com/15316131/117749628-f3642680-b1c6-11eb-9800-93ac462c7445.PNG)

Prior to this I was getting the lat/long error, and after adding per the instructions above, now if is just stuck.

Any help is greatly appreciated!

**Comment by davthomaspilot** [comment]
I just installed the latest Pool Control Dashboard.    I don't see the lat and lon entry boxes in the Personal Information dialog:

![pool](https://user-images.githubusercontent.com/6830886/120339363-0ef0b780-c2c3-11eb-8c30-e78094f1618a.JPG)

and I'm getting the warning:

Jun 01 10:18:20 alexa-2 node[2281]: [6/1/2021, 10:18:20 AM] warn: dt:Tue Jun 01 2021 10:18:17 GMT-0400 (Eastern Daylight Time) lat:undefined lon:undefined Not enough information to c

**Comment by tagyoureit** [comment]
It looks like you are on an old version of dashPanel.  Please run `git pull` and `npm i` assuming you have already done a `git clone https://github.com/rstrouse/nodejs-poolController-dashPanel.git` to initially load the app.
If you haven't updated the original app you should also update njsPC app itself.

**Comment by davthomaspilot** [comment]
I couldn't do a git the first time--I was too lazy to recall how to set up a public key.
But, I did do a download of the zip file.  Is that the same?
when you say "njsPC", you mane nodejs-poolController, right?  (versus a tag for a release or something like that)
    On Wednesday, June 2, 2021, 01:36:18 AM EDT, tagyoureit ***@***.***> wrote:  
 
 


Oh, and if you did pull the latest dashPanel make sure you do a hard refresh (Ctrl-F5) and that will load the latest versions of the files.

**Comment by davthomaspilot** [comment]
I got errors many minutes after doing the npm start.  So, I made a public get and did a git clone:

git clone ***@***.***:tagyoureit/nodejs-poolController.git

Will that give me the latest pool controller?
I'll do the same for dashPanel, once I confirm last night's fix in poolController works.    On Wednesday, June 2, 2021, 08:34:04 AM EDT, ***@***.*** ***@***.***> wrote:  
 
  I couldn't do a git the first time--I was too lazy to recall how to set up a public key.
But, I did do a download of the zip file.  Is that the same?
when you say "njsPC", you mane nodejs-poolController, right?  (versus a tag for a release or something like that)
    On Wednesday, June 2, 2021, 01:36:18 AM EDT, tagyoureit ***@***.***> wrote:  
 
 


Oh, and if you did pull the latest dashPanel make sure you do a hard refresh (Ctrl-F5) and that will load the latest versions of the files.

**Comment by davthomaspilot** [comment]
doing a git pull resolved the issue.  I didn't do the hard refresh.
