### ISSUE TITLE
Invalid body assignment, test branch, orp and ph

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#253]
![Invalid body assignment](https://user-images.githubusercontent.com/8471168/103364637-477a3400-4a8c-11eb-94f1-b5932543365d.JPG)
![Invalid data error](https://user-images.githubusercontent.com/8471168/103364639-4812ca80-4a8c-11eb-82ab-8b1bf16ffcbb.JPG)

I only get Intellichem showing in dashPanel when I am on "Test" branch. This was working fine at some point changing PH and ORP setpoints. Currently I get this error message about "Invalid body assignment" and can not change setpoints.

**Comment by rstrouse** [comment]
I'll have a look.  We have been adding quite a bit to the chemistry control lately so it is possible we got the body assignments twisted up.  If I remember, which OCP are you running?

**Comment by miamijerry** [comment]
Easytouch2 8 aux

**Comment by rstrouse** [comment]
Thanks.  I assume with the Easytouch 8 you don't get to specify whether it is for the pool, spa, or both.  Is that correct?

**Comment by rstrouse** [comment]
@miamijerry -- I removed the references for the body when attached to an EasyTouch system.  Pull next and dashPanel.  You should also now be able to set your tank level by clicking on the chem tank.  There are lots of changes and enhancements to the display for the dosing to include when the controller is dosing, what it is dosing at the time, and even how much is left but neither I or @tagyoureit have an IntelliChem to test this with so when you get a chance it would be great to see the output displayed when IntelliChem is dosing, mixing, and monitoring.
![image](https://user-images.githubusercontent.com/47839015/103382414-d0e93080-4aa3-11eb-8f7c-0cba18e639db.png)

**Comment by miamijerry** [comment]
Yes on the Easytouch 8 there is no selection for whether the PH and ORP setpoints are attached to a body.

Thanks, I will provide feedback

**Comment by miamijerry** [comment]
Working fine, Thank You
![Intellichem](https://user-images.githubusercontent.com/8471168/103403929-ec921c80-4b1f-11eb-96fb-68f6b8ca49e0.JPG)
