### ISSUE TITLE
Black color palette icon disappeared, can not access intellibrite control

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#255]
The intellibrite black icon which provides access to colors and other controls disappeared. This is on both master and next branches.

![intellibrite icon missing](https://user-images.githubusercontent.com/8471168/103446700-8f49b880-4c50-11eb-9a81-271227258e5a.JPG)

**Comment by rstrouse** [comment]
When you are running the purple theme it changes to white and I see it in your screenshot.  If you are running EasyTouch or IntelliTouch, each light doesn't have the ability to set individual IntelliBrite themes so the icon gets moved to the header because you can only have one IntelliBrite control in those systems which control all lights.

Below is the view from IntelliCenter.  The palette button exists on each light because each light can have its own theme and color.
![image](https://user-images.githubusercontent.com/47839015/103447077-61a64480-4c3b-11eb-8c2b-d193dffceead.png)

**Comment by miamijerry** [comment]
The white icon is not clickable. There was both a white and black icon before, the black icon was just below the white icon. Only the black icon has been clickable for me.

May have changed when the "invalid assignment issue" got fixed ??

**Comment by rstrouse** [comment]
EasyTouch2 8 right?  It looks like there were changes to how the IntelliBrite light groups were managed.  Can you upload your poolState.json and poolConfig.json so I can see how they differ from IntelliCenter.

**Comment by miamijerry** [comment]
[poolConfig.zip](https://github.com/tagyoureit/nodejs-poolController/files/5759708/poolConfig.zip)
[poolState.zip](https://github.com/tagyoureit/nodejs-poolController/files/5759709/poolState.zip)

**Comment by rstrouse** [comment]
Thank you!

**Comment by rstrouse** [comment]
@miamijerry - pull njspc and dashPanel.  I made changes to support the new way light themes are being handled.  Don't forget to hard refresh your browser in dashPanel.

**Comment by miamijerry** [comment]
Thanks, Working again!
![Working again](https://user-images.githubusercontent.com/8471168/103464424-882eb300-4d01-11eb-9c73-087f03ce49ef.JPG)

**Comment by miamijerry** [comment]
![Invalid Equipment ID](https://user-images.githubusercontent.com/8471168/103564403-6d3c7a00-4e8c-11eb-9043-39c286b31b0e.JPG)
When I go to select a color, I get an error
Invalid Equipment ID
Easytouch2 8

**Comment by rstrouse** [comment]
Please grab the latest njspc and dashPanel.

**Comment by miamijerry** [comment]
Pulled the latest and the issue is the same.

[poolConfig.zip](https://github.com/tagyoureit/nodejs-poolController/files/5778320/poolConfig.zip)
[poolState.zip](https://github.com/tagyoureit/nodejs-poolController/files/5778321/poolState.zip)

**Comment by rstrouse** [comment]
When you say select color do you mean a lighting theme or are you referring to individual colors for sAM modes?
The interesting thing is that your IntelliBrite group contains a light circuit that is not defined.
```
    {
      "id": 192,
      "master": 0,
      "circuits": [
        {
          "id": 0,
          "position": 0,
          "master": 0,
          "isActive": false
        },
        {
          "id": 2,
          "circuit": 4,
          "position": 1,
          "color": 4,
          "swimDelay": 5,
          "master": 0,
          "isActive": true
        }
      ],
      "isActive": true,
      "name": "Intellibrite",
      "type": 3,
      "lightingTheme": 194
    }
```
That circuit 0 is not valid.  I only see 1 IntelliBrite light in your circuits.

**Comment by miamijerry** [comment]
Party, Romance, Caribbean, American, Sunset, Royal, Blue, Green, Red, White, and Magenta, are all working.

Can the undefined entries be deleted?

**Comment by rstrouse** [comment]
The color section is really for sAM modes and these are typically related to multiple light circuits.  I will have a look at the Touch code to see what I see in relation to this.  In the meantime perform the following steps. 
1. please stop njspc.
2. Remove the circuit with id:0 from the JSON array including the comma.
3. Change the id for the circuit identified as 2 to 1.

In the end your IntelliBrite light group should look like the following.  After you have completed the edit save the file and restart njspc.
```
    {
      "id": 192,
      "master": 0,
      "circuits": [
        {
          "id": 1,
          "circuit": 4,
          "position": 1,
          "color": 4,
          "swimDelay": 5,
          "master": 0,
          "isActive": true
        }
      ],
      "isActive": true,
      "name": "Intellibrite",
      "type": 3,
      "lightingTheme": 194
    }
```

**Comment by miamijerry** [comment]
Performed edit as detailed.

Operates perfectly

Thanks
