### ISSUE TITLE
Make compatible with LAN protocol adapters.

### ISSUE THREAD

**Issue by bkhall** [tagyoureit/nodejs-poolController#256]
Description clearly states that a RS485 adapter is required.

Pentair has a networkable protocol adapter - P/N 520489.

Make this library capable of communicating with the adapter.

**Comment by tagyoureit** [comment]
This app supports multiple platforms that all communicate over RS485. Not all platforms support network interfaces and the ones that do vary. 

If you want to interact with the system via network protocol check out this project: https://github.com/parnic/node-screenlogic
