### ISSUE TITLE
Super Chlor can not be cancelled

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#260]
Easytouch2 8

Can start "Super Chlor" function just fine from dashPanel, but for the time period set for super chlor, I can not turn off pool. The pool is locked out by the super chlor function.

dashPanel does not have a Cancel button for Super Chlor

I can sent put command to poolController to cancel the Super Chlor, from mcsMQTT;
[1/9/2021, 10:02:13 AM] info: [10:02:13 AM] 192.168.0.103 PUT /state/chlorinator/superChlorinate {"id":1,"superChlorinate":false}
but poolController or Easytouch is not cancelling the Super Chlor.

Autelis system is able to cancel the Super Chlor without issue.

**Comment by rstrouse** [comment]
Actually, that is not true.  If the superChlor is engaged then the button changes to Cancel.  There might be an issue with the Touch settings.  Are you not seeing this?

![image](https://user-images.githubusercontent.com/47839015/104106829-10b2d380-526d-11eb-8488-1fd0242228c7.png)

**Comment by tagyoureit** [comment]
Per the [MQTT documentation](https://github.com/tagyoureit/nodejs-poolController/wiki/Bindings-Integrations-in-2.0#set-values-with-mqtt), /state/chlorinator/superChlorinate is not implemented.

**Comment by miamijerry** [comment]
We are sending PUT commands the same as dashPanel
![Super Chlor button](https://user-images.githubusercontent.com/8471168/104111880-a70ae780-52b5-11eb-9bd5-f30519d7a4ee.JPG)
Easytouch2 8, no cancel button is displayed

**Comment by miamijerry** [comment]
Cancel button now working fine on Easytouch2 8 with poolcontroller 6.1.1 build 909
