### ISSUE TITLE
Solar temperature not being captured and displayed

### ISSUE THREAD

**Issue by antamy** [tagyoureit/nodejs-poolController#265]
I have an Intellitouch i5+3S system with solar water heating panels, with a valve that is actuated based on solar temperature.  The Intellitouch display (Menu/Setup/Equipment/Solar) has Water Solar Present = Yes and Solar Is A Heatpump = No).  The Temp Diff screen from this menu displays a value for the current Solar Temperature.

Solar temperature is displayed as 0 in the UIs and also from /state/temp.
[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/5920575/replay.zip)

**Comment by rstrouse** [comment]
By chance do you know what the solar temps should have been at the time you captured the replay?

Perhaps:
Air Temp = 58F
Solar Temp = 60F

**Comment by antamy** [comment]
Yes, those are correct!



________________________________

**Comment by rstrouse** [comment]
Ok so I modified the code to pull the air temp and solar temp in IntelliTouch.  You will need to switch to the next branch.

Navigate to your nodejs-poolController directory and type the following commands.
```sudo git checkout next```
```sudo git pull```

Then restart njspc.

**Comment by antamy** [comment]
> 
> 
> Ok so I modified the code to pull the air temp and solar temp in IntelliTouch. You will need to switch to the next branch.
> 
> Navigate to your nodejs-poolController directory and type the following commands.
> `sudo git checkout next`
> `sudo git pull`
> 
> Then restart njspc.

Not sure if my email to you went through, but this is now all working!  Thanks!

**Comment by tagyoureit** [comment]
Closing this to continue with replays on #266.
