### ISSUE TITLE
Pentair IntelliPH?

### ISSUE THREAD

**Issue by brentratliff** [tagyoureit/nodejs-poolController#267]
Any idea it this will work with IntelliPH? In the market to add acid and chlorine pumps for automation.

**Comment by brentratliff** [comment]
Not sure if others want this answered, but I went with an Intellichem which I know works. Thanks for the good work on this.

**Comment by tagyoureit** [comment]
See https://github.com/tagyoureit/nodejs-poolController/issues/124.  IntelliPh doesn't send packets on the RS485 bus, it seems to have a listen-only mode.

**Comment by johnny2678** [comment]
Yep, I recently removed the IntelliPH control board because I couldn't interact with it over the bus.  I kept the tank/pump and wired up my own automation.  Now, whenever pH readings get too high, the pool gets a quick dose from the acid pump via a solid state relay powered by a raspberry pi.

**Comment by tagyoureit** [comment]
That's exactly what we built REM (relay equipment manager) for.  It's a companion for 6.5.0 and controls gpio, spi and i2c devices.

![2021-02-13_09-20-06](https://user-images.githubusercontent.com/1646840/107856406-d218b780-6ddc-11eb-8f04-ad46b7b86cb0.png)

![2021-02-13_09-19-51](https://user-images.githubusercontent.com/1646840/107856408-d513a800-6ddc-11eb-9f9c-d6780ae7b889.png)
