### ISSUE TITLE
MQTT topic mismatch - orpDosingVolume <> pHDosingVolume - mqtt.json line 392

### ISSUE THREAD

**Issue by johnny2678** [tagyoureit/nodejs-poolController#269]
mqtt.json line 392

```
        {
          "topic": "state/chemControllers/@bind=data.id;/@bind=data.name;/orpDosingVolume",
          "message": "{\"pHDosingVolume\":@bind=data.orp.doseVolume;}"
        },
```

shows up like this in MQTTexplorer: 
![image](https://user-images.githubusercontent.com/8219743/108757600-0e07f700-7518-11eb-92f6-31c10b79a5f6.png)

I've never done a pull request before but I can try fix.

edit: sorry - don't know how to do a pull request 😂

edit2: actually looks like line 388 is transposed too

```
        {
          "topic": "state/chemControllers/@bind=data.id;/@bind=data.name;/pHDosingVolume",
          "message": "{\"orpDosingVolume\":@bind=data.ph.doseVolume;}"
        },
```

**Comment by rstrouse** [comment]
This has been resolved in next.
