### ISSUE TITLE
Schedules running on wrong day?

### ISSUE THREAD

**Issue by johnny2678** [tagyoureit/nodejs-poolController#270]
Not sure if this is a UI issue or a schedule issue.  Or just isolated to my environment.

3 days a week, I run my pool at a higher RPM for an hour in the morning to let the in-floor cleaning swivel returns do their thing.  I set the schedule for Mon, Weds, Fri.

However, it's running this morning (tues):
![image](https://user-images.githubusercontent.com/8219743/108849209-e5cbd700-75af-11eb-9b9e-480e8e726bb9.png)

At first I thought I set the schedule wrong. The X's in the UI are a little confusing.  Is it, or is it not supposed to run on the day with the X in the circle?

But then I confirmed in settings that I set it for Mon/Weds/Fri:
![image](https://user-images.githubusercontent.com/8219743/108849377-14e24880-75b0-11eb-8a65-66ce7643360e.png)

Any ideas why it's running today? Tues?  This isn't isolated to today... it's been doing this for a while.  I won't run tomorrow (Weds), but will run on Thurs, etc.  No harm done as I'm still getting every other day.  

Not sure what log info I can provide after the fact.  Do you want me to run a packet capture tomorrow (weds) morning when the schedule is supposed to run so you can see what's happening?  and again Thurs morn when it does run, but isn't scheduled to? 

Low priority, just bringing it up because it's been a head scratcher for me.

**Comment by johnny2678** [comment]
Another interesting observation @rstrouse @tagyoureit ... this morning (Sat) the schedule for Pool High ran, which is only supposed to run on Mod,Weds,Fri

![image](https://user-images.githubusercontent.com/8219743/109388610-268c5e80-78d6-11eb-907e-1fe73aa839fe.png)

Pool High operates at 2760 rpm so you can see that the pump is actually running the schedule, it's not just in software.

But, the OCP reports that the schedule isn't running.  Even though the corresponding Pool High feature is on.

![IMG_0717](https://user-images.githubusercontent.com/8219743/109388975-46248680-78d8-11eb-9df6-97a55612a118.PNG)

I missed the logs/packet capture this morning when the schedule started.  Will try and get them for next time.

**Comment by rstrouse** [comment]
EasyTouch does not report any indicator that a schedule happens to be in effect.  The code we were using synthesizes this effect by looking at the current time and the circuit to determine whether the schedule should be running.  However, it was not looking at the day of the week correctly.  If you pull this should be fixed in next.

Please note that there is no code that engages the circuit from njspc related to the schedule.  If the Pool High circuit is on, I can find no code where njspc turned it on.

**Comment by johnny2678** [comment]
interesting.... I'll pull `next` and keep observing.  Not a big deal.  Instead of the schedule running Mon/Weds/Fri, it runs Tues/Thurs/Sat.

**Comment by rstrouse** [comment]
I don't have an EasyTouch but it is very odd that it registers on your ScreenLogic as Mon/Wed/Fri and actually runs on Tues/Thurs/Sat.  I seem to remember when I had IntelliTouch I had to actually tell it what the day of the week was.  Are you sure that is set correctly on the EasyTouch panel.

**Comment by johnny2678** [comment]
omg... of course it's the easiest explanation.

I didn't even think my pool could be set incorrectly.  Thought my phone app had me covered with time sync:

![IMG_C144523475EA-1](https://user-images.githubusercontent.com/8219743/109394799-dc67a500-78f6-11eb-980b-8a2261f0e56c.jpeg)

and then I thought i was double covered with njspc:
![image](https://user-images.githubusercontent.com/8219743/109394818-ef7a7500-78f6-11eb-928a-5ed1526daf7a.png)


didn't even enter my mind that the ocp could be off by a day, but sure enough, my pool thinks it's fri 🙄

![IMG_0718](https://user-images.githubusercontent.com/8219743/109394840-1d5fb980-78f7-11eb-8752-55ccfdcb8a33.jpg)

**Comment by rstrouse** [comment]
Look at that you get an extra day.  With that kind of logic you should be able to schedule for the second Tuesday of the the week.

**Comment by tagyoureit** [comment]
By the way, there's a setting for that.

<img width="643" alt="2021-02-28_19-19-05" src="https://user-images.githubusercontent.com/1646840/109448058-fb029480-79f9-11eb-809e-bc19432ed567.png">

If you choose "server" then njsPC will check your *Touch system time (every 5 mins) and correct it when it is off by >5 mins.

**Comment by johnny2678** [comment]
> BTW, how did you get it to say "Fri Feb 27". Where I live, the 27th was Saturday.??

I know, right???

My guess is it’s been like that since Feb 29th of 2020 and the extra leap day threw it off.

All of my schedules are ‘every day’ schedules except that one so it took me a while to notice.
