### ISSUE TITLE
Can't read data from IntelliCenter

### ISSUE THREAD

**Issue by Candurin** [tagyoureit/nodejs-poolController#284]
**Describe the bug**
I am so close. I have activity LEDs on the USB adapter now (https://www.amazon.com/gp/product/B07SD65BVF).  However, when I start the NodeJS Pool Controller I get stuck on this warning in a continuous loop 
"**[4/29/2021, 10:24:54 AM] warn: The body temperature for Pool cannot be determined. Heater status for this body cannot be calculated.**"

Then I noticed that when I start dashpanel, I see this: 

**info: Server is now listening on 0.0.0.0:5150
192.168.1.48 GET /config/web.services?null
192.168.1.48 GET /config/web.services?null
192.168.1.48 GET /
192.168.1.48 GET /config/web.services?null
192.168.1.48 GET /config/web.services?null
192.168.1.48 GET /options?null
192.168.1.48 GET /config/findPoolControllers?null
done searching for poolController
192.168.1.48 PUT /config/web.services
192.168.1.48 GET /config/web.services?null
192.168.1.48 GET /config/web.services?null
192.168.1.48 GET /options?null
192.168.1.48 GET /
192.168.1.48 GET /config/web.services?null
192.168.1.48 GET /config/web.services?null**

Which seems odd because my Pi is statically set at 192.168.1.50

**Screenshots**

![Screen Shot 2021-04-29 at 10 44 56 AM](https://user-images.githubusercontent.com/83413612/116570137-0548ee00-a8d8-11eb-86bb-e90dfd8d6971.png)

**Pool Equipment**
 - Controller: IntelliCenter
 - Controller Model: IntelliCenter i5PS
 - Controller Firmware Version: 1.047
 - Pump(s) manufacturer and model: IntelliFlow 2 VST 011056
 - Chlorinator: IntelliChlor-40
 - Heater(s): MasterTemp 300
 - Chemical controller: N/A
 - Valves: Manual

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.2)
 - Browser: Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.5
 - Browser: Safari

**Comment by rstrouse** [comment]
Alright now that you have communication with the RS485, perform the following steps.  

1. Shut down njspc.
2. From the directory where nodejs-poolController is installed pull the latest code `git pull` just to make sure you have all the updates.
3. Delete the files in the data directory.  There should be 2 of them poolState.json and poolConfig.json.
4. Restart njspc `npm start`

Now that IntelliCenter is broadcasting status njspc should be able to hear the controller on the bus and create the necessary items to operate as a slave to IntelliCenter.

**Comment by Candurin** [comment]
Followed all your steps.  No dice:

<img width="1112" alt="Screen Shot 2021-04-29 at 1 09 49 PM" src="https://user-images.githubusercontent.com/83413612/116591376-bce7fb00-a8ec-11eb-9d43-1c9a4a048404.png">

**Comment by rstrouse** [comment]
Hmmm.  IntelliCenter is powered up when you start?

**Comment by Candurin** [comment]
It's running.  I can access it from the app and website.  

Do you think I should move the communications from the IntelliChlor "daughter card" comm port and combine with another device on the IntelliCenter comm port (perhaps the one shared by the pump)?

**Comment by rstrouse** [comment]
This actually looks like the data + and - are reversed.  What will happen then is every message sent will be invalid.  Double check the wiring.  If the connections are good and tight reverse the green and yellow wires on the adapter.

**Comment by Candurin** [comment]
Changed yellow and green at the USB adapter:<img width="1103" alt="Screen Shot 2021-04-29 at 2 08 34 PM" src="https://user-images.githubusercontent.com/83413612/116598106-739ba980-a8f4-11eb-9a14-2c2b95e9b798.png">

It still doesn't say IntelliCenter, but that much closer!

**Comment by rstrouse** [comment]
After you did that did you delete the files in the data directory and restart?
If you did then lets make sure we are addressing the right USB port.  Sometimes these adapters don't install at ttyUSB0.

Do you know how to list the available ports on the pi?

**Comment by Candurin** [comment]
Hold that thought!  I clicked on "reload configuration".  Voila!<img width="1108" alt="Screen Shot 2021-04-29 at 2 11 10 PM" src="https://user-images.githubusercontent.com/83413612/116598400-c9705180-a8f4-11eb-86ff-7db25619fecf.png">

Which is crazy because I have it connected Yellow to A+ and Green to B- on my adapter.  Maybe the adapter is wired incorrectly?

Either way, thanks!

**Comment by rstrouse** [comment]
The reason why we have you switch the wires is because those adapters are rarely documented well and sometimes incorrectly.  Glad you are up and running.  Enjoy!

**Comment by Candurin** [comment]
Any ideas how to make my pi autostart the controller and dash panel?  I edited the local file but no luck there.

**Comment by rstrouse** [comment]
I use PM2 to start mine.  Check out the wiki for options
https://github.com/tagyoureit/nodejs-poolController/wiki/Automatically-start-at-boot---PM2-&-Systemd

**Comment by Candurin** [comment]
@rstrouse PM2 works great!  Everything up and running and auto-starting on reboot.  Again, the help was much appreciated.

**Comment by rstrouse** [comment]
I knew we would get you there.
