### ISSUE TITLE
Intelliflo VS 3050 read as VF

### ISSUE THREAD

**Issue by Telemachus1977** [tagyoureit/nodejs-poolController#292]
**Describe the bug**
VS 3050 pump is read as VF.  GPM are not reported, but watts are.

**To Reproduce**
Just shows up on home screen.

**Expected behavior**
I would expect to see VS with RPM

**Packet Capture**
Attached

**Pool Equipment**
 - EasyTouch 8 
 - Controller [EasyTouch2 8P]
 - Controller Firmware Version: [e.g. 2.060]
 - Pump(s) manufacturer and model: [e.g. Intelliflow VS 3050]
 - Chlorinator: [iChlor, IntelliChlor-40]
 - Heater(s): [gas]
 - Chemical controller:  none
 - Valves: standard
 - Raspi Zero W

**Desktop (please complete the following information):**
 - OS: [android]
 - Browser [e.g. chrome]
 - Version [22]

**Smartphone (please complete the following information):**
 - Device: [Note 9]
 - OS: [Android 10]

**Additional context**
Add any other context about the problem 

[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/6456016/replay.zip)

**Comment by rstrouse** [comment]
Just to be sure on this could you please check your setup in the EasyTouch panel.  This will be under Settings --> IntelliFlo --> Pump 1 the signature that is coming from EasyTouch is actually a VF pump.

@tagyoureit for reference here is the Action 24 message for that pump.  Byte(1) is 255.
`[255, 0, 255][165, 20, 15, 16, 24, 31][1, 255, 0, 255, 255, 6, 7, 1, 13, 11, 12, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 3, 8, 122, 28, 232, 232, 232, 232, 232, 232][10, 95]`

**Comment by Telemachus1977** [comment]
![20210509_204824](https://user-images.githubusercontent.com/25725743/118043494-49051400-b32a-11eb-8969-1879ab24cc9d.jpg)
![20210509_204820](https://user-images.githubusercontent.com/25725743/118043496-4a364100-b32a-11eb-9436-9241a8f1f1ba.jpg)
![20210509_204810](https://user-images.githubusercontent.com/25725743/118043497-4a364100-b32a-11eb-9edc-35a994848b90.jpg)

**Comment by rstrouse** [comment]
Actually what I want you to verify is the settings on the main panel.  I am not sure whether these actually exist in the handheld controller but the pump type not the speed is what I want you to verify.
![image](https://user-images.githubusercontent.com/47839015/118051426-d9952180-b335-11eb-9f57-92f296850994.png)

**Comment by Telemachus1977** [comment]
For sure I will verify that.

But as the handheld is reading RPM shouldn't njs-pC also read that data?

![Uploading Screenshot_20210510-133939_Chrome.jpg…]()

**Comment by rstrouse** [comment]
> But as the handheld is reading RPM shouldn't njs-pC also display that data?

Yes it should but the panel is reporting what we have seen in the past as a VF pump and RPM is not valid for that pump.  It sends out garbage in that spot.  I believe what we have found is simply a difference in the EasyTouch firmware.  Double checking that information will help us to map the signature to the proper pump type.  It is very odd that it is returning 255 which is way out of range for what we have seen VS pumps at in the past.  In fact 255 is typically what Pentair reports when it doesn't have a definition.  Either way we can coerce it if we are sure that the byte is actually set on the panel.

**Comment by Telemachus1977** [comment]
I do not even see anywhere on the menus where it gives me a pump type.  VS was the only option back in 2009 AFAIK.  RPM is all I have ever been able to program.

I have recieved my programmer and plan on updating my firmware in the next few weeks so this may be a moot issue.

**Comment by rstrouse** [comment]
That was my suspicion.  255 means that the byte never gets set.   I think it is safe for us to call that a VS pump.  I’ll let you know when we add it.  Probably tomorrow.

**Comment by Telemachus1977** [comment]
![20210513_060713](https://user-images.githubusercontent.com/25725743/118129844-8bbdff00-b3b1-11eb-80b7-db861e0eade6.jpg)
![20210513_060701](https://user-images.githubusercontent.com/25725743/118129875-97112a80-b3b1-11eb-9da4-d4832f0ccd5f.jpg)

Thanks.   Certainly a VS pump.

**Comment by Telemachus1977** [comment]
![20210513_060914](https://user-images.githubusercontent.com/25725743/118130256-06871a00-b3b2-11eb-9bd3-aba4cbf17b98.jpg)

**Comment by Telemachus1977** [comment]
![Screenshot_20210514-091629_Chrome](https://user-images.githubusercontent.com/25725743/118299043-20e5f400-b495-11eb-80d9-4a68929a11dc.jpg)

Updating the firmware to the newest available from Pentair has resolved this problem.

**Comment by rstrouse** [comment]
Thanks for letting us know.
