### ISSUE TITLE
Install Hanging

### ISSUE THREAD

**Issue by gambler2841** [tagyoureit/nodejs-poolController#296]
**Describe the bug**
While trying to install the package, after running 'npm start&', the connection to the RS485 adapter is successful, but hangs after that:

![image](https://user-images.githubusercontent.com/15316131/118043686-8b2e5580-b32a-11eb-9067-f02d883670af.png)

Prior to this I was getting the lat/long error (issue 245), but after entering the information into the poolConfig.json,, this is where i'm at. Not sure why it's hanging up. It is wired to the pool controller, but not connecting.

**To Reproduce**
1. Go to '...'  - npm start&
4. See error -  No error

**Expected behavior**
I expected connection to the pool equipment, or an error of why it cannot connect.

**Packet Capture**
Follow the instructions to complete a [packet capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution) and attach the resulting zip/log files.

**Pool Equipment**
 - Controller: Pentair Easytouch PL4/PSL4 Controll System

**Comment by rstrouse** [comment]
This is not hanging.  It is simply not hearing any information from your EasyTouch.  As a result njsPC is acting as a master controller for a single body system.  Once it detects traffic from an EasyTouch controller it will acquiesce to it and immediately start asking for information from the EasyTouch.

So based on our experience here, this means that either the adapter is bad, the serial port is not on /dev/ttyUSB0 or you have the wires backwards.  Bear in mind we have seen a ridiculous number of failed JBTek adapters lately.  The other thing we have seen are adapters with the printing backwards for the A-/B+ channels on RS485.  The way to check this is to simply swap the wires but you should shut down before you do it.  You do not want the two wires to touch.

**Comment by gambler2841** [comment]
Thanks for the quick response. I changed the A-/B+ and it found the controller. Now I'm stuck at this:

![image](https://user-images.githubusercontent.com/15316131/118059982-a1e2a580-b346-11eb-8b8b-b169d32dadf7.png)

Any ideas?

**Comment by rstrouse** [comment]
That line `Pentair EasyTouch System Detected` is actually data from the OCP.  However, the aborted message is common.  What does your poolConfig.json look like in the data directory?  It looks like the configuration actually completed. 

Are you running dashPanel and do you see your circuits and features?  Collisions and aborts are a normal part of an RS485 bus?

**Comment by gambler2841** [comment]
I haven't installed the dashPanel yet; I thought I had to have the connection to njsPC up and running completely first. I will try and install now. 

I can try and get the poolCongig.json, but i'm VNC'd into the Pi, so it's hard to get all the information. Is there something in particular you're looking for?

Thanks so much for the help! I'm a newbie and really appreciate it!

**Comment by rstrouse** [comment]
I am pretty sure that once you get dashPanel up and running this will all make sense.  The process you are looking at in the console is not locked or hung and it wasn't before.  If you had loaded up dashPanel you would have seen that it was a Nixie Single Body controller with all the fixins around that.  However, it should now say EasyTouch 2 8 in the header and the circuits, features, and schedules configured on your EasyTouch should appear on the screen.

**Comment by gambler2841** [comment]
So I installed the dashPanel. It went well. This is what I am getting when logging into the server (granted I am using Chrome on my Windows machine, which I would think would work?)

![image](https://user-images.githubusercontent.com/15316131/118067774-11ac5c80-b356-11eb-8a7e-ed75aaf2b08f.png)

**Comment by rstrouse** [comment]
Click on the hamburger on the upper left.  Then choose the connection tab and enter the address for njsPC and press apply.  The default port for njsPC will be 4200.  You can also choose to find the server but that is dependent on your network ability to supply upnp packets.

**Comment by gambler2841** [comment]
That did it! Thanks so much for your patience and help!

**Comment by rstrouse** [comment]
No worries glad you are up and running.
