### ISSUE TITLE
"service", "timeout" monitoring and control via MQTT

### ISSUE THREAD

**Issue by fgonza2** [tagyoureit/nodejs-poolController#304]
I am using HA with MQTT and SOCAT with a RS485 to wifi module. works great mostly :)

Is there a way to monitor and disable "service" or "timeout" mode via MQTT?

dashpanel shows it but you can't change it from there.   Let me know if there is a way or if not if this can be added as a feature

thanks

**Comment by rstrouse** [comment]
If you are using a Pentair OCP this can only be triggered from the main panel.  I have yet to find a way to coerce the panel into timeout or service more or kick it out of it.

**Comment by fgonza2** [comment]
Got it.  Is there a way to monitor the state via MQTT?

**Comment by rstrouse** [comment]
These should now emit on the controller MQTT topic.

**Comment by fgonza2** [comment]
great will try it out tonight thanks!

**Comment by tagyoureit** [comment]
Please re-open if this is not fixed.
