### ISSUE TITLE
remove expressDir setting from config.json

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#31]
This shouldn't be needed now that everything is running under from the /www directory.

If you are finding this error, or not getting any web page returned, use this setting: `"expressDir": "/www",`

**Comment by arrmo** [comment]
Yes, agreed! Remove this, and just hard code it ... default set up, and different UI's can be added easily then.

Did you make this change? I can pull and test it.

**Comment by tagyoureit** [comment]
Not yet.  I should be able to get it done soon.  This is an easy change.

**Comment by tagyoureit** [comment]
Just pushed up.  Re-open this if any issues...

**Comment by arrmo** [comment]
Works just fine - thanks!
