### ISSUE TITLE
Pump cycling on and off

### ISSUE THREAD

**Issue by Elecverton** [tagyoureit/nodejs-poolController#317]
When running the nixie single body with an inteliflow pump I can start the pump via dash panel, but I get error messages as per below and every few minutes the pump stops and then starts again at full speed (priming) and then goes to the selected speed. This runs for a few minutes (with the error messages continuously scrolling by) and the process repeats.

[6/7/2021, 2:12:12 PM] error: Error sending setDriveState for Pump : Message aborted after 2 attempt(s): 165,0,96,33,6,1,10,1,55
[6/7/2021, 2:12:12 PM] error: Error running pump sequence for Pump: Message aborted after 2 attempt(s): 165,0,96,33,6,1,10,1,55
[6/7/2021, 2:12:12 PM] error: Nixie Error running pump sequence - OutboundMessageError: Message aborted after 2 attempt(s): 165,0,96,33,6,1,10,1,55

SW version: Njspc 7.1.0
Firmware 1.0.0

Capture:
[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/6611176/replay.zip)

**Pool Equipment**
 - Controller: N/A
 - Controller Model: N/A
 - Controller Firmware Version: N/A
 - Pump(s) manufacturer and model: IntelliFlow 2 VST 011056]
 - Chlorinator: IntelliChlor-40
 - Heater(s): N/A
 - Chemical controller: N/A
 - Valves: N/A
 - Any other relevant equipment: N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version [e

**Additional context**
USB to RS-485 adapter: DSD Tech Model SH-U10

**Comment by tagyoureit** [comment]
Hi, there are a few things going on here, and I'm not at a place where I can entirely reconfigure my pool to test it out but I think I know what's going on.

1. As a general best practice, you should assign your lowest speeds for the pump to the Pool circuit.  You currently have 2000rpm, 2500rpm, Chem Circulate.  You should assign the Pool Circuit to the pump at the 2000 Rpm.  Thereafter, you don't need to turn on the pool separately from selecting a speed.  If you want to bump up the speed to 2500rpm, you should leave the Pool circuit (now 2k rpm) on, and also turn on the 2500rpm circuit (highest speed wins).

2.  You have the maximum speed for the pump to be 3,000 rpm but you set the Chem Circulate group to 3,450 rpm and hence we are ignoring it.  This is something I also fixed on our end (you should now see the 3450 rpm circuit running at the maximum defined pump speed of 3000 rpm).

3.  I fixed the circuit group not showing up in the features display.

Pull njsPC and dashPanel and please try this again.

**Comment by Elecverton** [comment]
It seems that there the controller throws errors when my IC-40 chlorinator is part of the config and turned on.  If the chlorinator is in the config, but the pool circuit is not selected (ie. chlorinator is off), everything appears to work fine.  if I then turn on the pool circuit (which turns on the chlorinator) I then get write errors below. 

warn: Message aborted after 2 attempt(s): 165,0,96,33,6,1,4,1,49
[6/12/2021, 11:22:29 PM] error: Error sending setDriveState for Pump : Message aborted after 2 attempt(s): 165,0,96,33,6,1,4,1,49
[6/12/2021, 11:22:29 PM] error: Error running pump sequence for Pump: Message aborted after 2 attempt(s): 165,0,96,33,6,1,4,1,49
[6/12/2021, 11:22:29 PM] error: Nixie Error running pump sequence - OutboundMessageError: Message aborted after 2 attempt(s): 

I've also noticed error packets from the chlorinator as per below:
[6/12/2021, 11:58:14 PM] debug: We have an incoming chlorinator message but the serial port hasn't given a complete header. [][][16,2,0]
[6/12/2021, 11:58:14 PM] info: {"id":4228,"valid":true,"dir":"in","proto":"chlorinator","for":[4227],"pkt":[[],[],[16,2,0,3],[0,73,110,116,101,108,108,105,99,104,108,111,114,45,45,52,48],[188,16,3]],"ts": "2021-06-12T23:58:14.068-0400"}

I have run 2 captures as requested.  One with the chlorinator inthe config and another without.  In each capture, I start by running the pump with the pool circuit off and run through speeds 2000, 2200, 2500, 2200, 2000.  I then run the pool circuit (which is set at 1950).  The config with the chlorinator immediately erros, but tehe config without a chlorinator runs without error.

[replay without Intellichem.zip](https://github.com/tagyoureit/nodejs-poolController/files/6643257/replay.without.Intellichem.zip)
[replay with IntelliChem.zip](https://github.com/tagyoureit/nodejs-poolController/files/6643258/replay.with.IntelliChem.zip)

**Comment by tagyoureit** [comment]
I did some work on another branch to check out these issues.  Can you pull this commit? (5df40ac) 

1. git checkout ResponseRefactor
1. git pull
1. Restart app.

Let's see if the same thing happens...

**Comment by Elecverton** [comment]
I'll try it shortly and get right back to you.

Thanks!

**Comment by Elecverton** [comment]
I seem to be getting the same behaviour.  I am seeing the below error even before I start the pump (ie. poolcontroleer has started, but dashpanel in not even running yet)
[6/19/2021, 3:40:01 PM] error: Error sending setDriveState for Pump : Message aborted after 2 attempt(s): 165,0,96,33,6,1,10,1,55
[6/19/2021, 3:40:01 PM] error: Error running pump sequence for Pump: Message aborted after 2 attempt(s): 165,0,96,33,6,1,10,1,55
[6/19/2021, 3:40:01 PM] error: Nixie Error running pump sequence - OutboundMessageError: Message aborted after 2 attempt(s): 165,0,96,33,6,1,10,1,55

Do you want more captures or some specific test to be run?

**Comment by tagyoureit** [comment]
Yes, one more please. Please set the packet capture and then completely shut down the app, restart and then send the logs after a couple of mins after you see the first error. Thx.

**Comment by tagyoureit** [comment]
Didn't mean to close this...

**Comment by Elecverton** [comment]
I've been playing with this for a few days now and realizing that it isn't consistent.  I've had several instances where everything appeared to work fine for several hours and then errors start appearing.  I'm starting to think it may have to do with HW.  I'll need to check, but I think my Pi's power supply is isolated and the common mode range of the RS-485 IC may be getting violated without a reference.  I'll try to check that later today.

I've attached some logs from my last test last night where everything was running fine, so I went to bed and let it run most of the day (I couldn't check it in the morning).  Turns out that everything worked fine for 1.5 hours when the pump wa getting turned back on and then there are errors from that point on.

Hopefully the packet log isn't too big.

[consoleLog(2021-06-22_23-30-03).log](https://github.com/tagyoureit/nodejs-poolController/files/6704201/consoleLog.2021-06-22_23-30-03.log)
[packetLog(2021-06-22_23-30-03).log](https://github.com/tagyoureit/nodejs-poolController/files/6704204/packetLog.2021-06-22_23-30-03.log)

**Comment by tagyoureit** [comment]
was this with the responseRefactor branch?  Or back on the master branch?

**Comment by Elecverton** [comment]
Yes it was

**Comment by tagyoureit** [comment]
I'm not seeing the pump responses related to the outbound, which is what was fixed in the branch I pushed up.  What is in your poolState.json under the appVersion section?

**Comment by Elecverton** [comment]
Looks like the pull didn't work like I thought.

  "appVersion": {
    "installed": "7.1.0",
    "status": {
      "val": 0,
      "name": "current",
      "desc": "On current version"

I'll try pulling again.  I must have typed it wrong the 1st time and didn't realize.  sorry.  I'll try again.

**Comment by tagyoureit** [comment]
Please re-open if you still have issues.  Hope it's fixed since we haven't heard from you in a while.
