### ISSUE TITLE
Chlorinator goes offline when setting to 16%

### ISSUE THREAD

**Issue by truvec** [tagyoureit/nodejs-poolController#338]
Chlorinator goes offline when setting it to 16%. On the Aquarrite the no flow led blinks and the controlled remotely led goes off. This happens when set via Pool Control dashboard or via MQTT.

I have a Nixie single body with intelliflo vs and Hayward aquarite.

[replay 2.zip](https://github.com/tagyoureit/nodejs-poolController/files/7049436/replay.2.zip)

**Comment by tagyoureit** [comment]
![Chlor 16](https://user-images.githubusercontent.com/1646840/132043369-fb556b1d-05a2-4453-b3b8-7f7188475deb.png)

I had a chance to look into this for a few minutes, and, well color me silly... this is something new.  The packets for setting the chlor to 15% and 17% are the same, but the packet for 16% has an extra 0 in the payload.  I don't think I've ever seen anything like that before.  

Pull the latest.
I'll push up a fix for this in a bit.

**Comment by truvec** [comment]
OK- Yes it does now set to 16%. Do you need to see the output? 

Thanks!

**Comment by tagyoureit** [comment]
Nope, all good.  Thanks for confirming.  Sweet 16!!!
