### ISSUE TITLE
Aquacal PoolSync Compatibility?

### ISSUE THREAD

**Issue by dfizzo** [tagyoureit/nodejs-poolController#352]
Hi - is this platform compatible with the AquaCal PoolSync controller? I am looking for best way to to control my AquaCal heat pump (Sunblazer) and AquaCal chlorinators (AutoPilot Nano+). Trying to determine either I need the PoolSync controller or should just go with basic RS-485 approach. Really appreciate any guidance you can provide as I'm at an impasse on this project. Thanks!

@dfizzo￼￼

**Comment by rstrouse** [comment]
Some of the AquaCal models support the same protocol as the Pentair UltraTemp and can be controlled over RS485.  Other AquaCal models can be controlled via their fireman's switch.   You will not have any luck with the PoolSync controller and this software.   

For the chlorinator if it uses the similar protocols as the AquaRite or IntelliChlor chlorinators then it should work but if it doesn't perhaps there is something we might be able to do to drive it.  I believe their Autopilot line used to be supported by Jandy using the Hayward protocol so perhaps there is a chance.

My recommendation is to install the software with an RS-485 connection to the Autopilot and the AquaCal using one of the Nixie controller configurations then we can see whether we can wake up the Autopilot to at least tell us what the status is.  If your heat pump model is not compatible with Pentair automation then it should be able to be controlled via the fireman's switch interface.

**Comment by dfizzo** [comment]
Thanks so much for the quick response and detailed response! I will proceed on this basis and let you know once I get it all organized. Much appreciated!!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Oct 6, 2021, at 2:59 PM, rstrouse ***@***.***> wrote:

﻿
Some of the AquaCal models support the same protocol as the Pentair UltraTemp and can be controlled over RS485. Other AquaCal models can be controlled via their fireman's switch. You will not have any luck with the PoolSync controller and this software.

For the chlorinator if it uses the similar protocols as the AquaRite or IntelliChlor chlorinators then it should work but if it doesn't perhaps there is something we might be able to do to drive it. I believe their Autopilot line used to be supported by Jandy using the Hayward protocol so perhaps there is a chance.

My recommendation is to install the software with an RS-485 connection to the Autopilot and the AquaCal using one of the Nixie controller configurations then we can see whether we can wake up the Autopilot to at least tell us what the status is. If your heat pump model is not compatible with Pentair automation then it should be able to be controlled via the fireman's switch interface.

**Comment by rstrouse** [comment]
I am closing this for now.  Let us know if you need more help.

**Comment by dfiore1230** [comment]
I have a similar setup and i haven’t had any luck, i see 100% serial failure rate when trying to communicate with my poolsync / chlorsync30

Happy to debug as necessary, I am keen on getting this supported.

Dave

**Comment by rstrouse** [comment]
Please start a new discussion or issue.  This issue has been closed.  It would be good to hook up njsPC to the RS485 bus and control the heater and chlorinator while njsPC is capturing a replay.

**Comment by mguinness** [comment]
@dfiore1230 Which baud rate were you using 9600 or 19200?  You should open a new issue and the folks here can help you figure it out.

**Comment by dfiore1230** [comment]
I put that project on the shelf for now. Pool is closed for the year so will pick it up in May

**Comment by rb2k** [comment]
Just for future archeologists:

The Aquacal website has a section thatm entions RS485:

[Connecting External Controllers to Heat Pump](https://www.aquacal.com/wp-content/uploads/manuals/landingpage/great_big_bopper_installer_hp9/Content/Resources/Topics_Manuals_QS/Mini%20TOC%20Pages/External%20Controllers.htm)

**Comment by rstrouse** [comment]
So did you get it to work?

**Comment by rb2k** [comment]
I'm still waiting for my RS485 adapter. I mainly wanted to point out the official documentation about that specific aquacal heat pump hardware and the two ways they suggest to hook them up (RS-485 for Smart Bus Controllers or 2 wire).

**Comment by rstrouse** [comment]
It will be interesting to see if it talks via the UltraTemp protocol.  njsPC supports it already so define the heater as UltraTemp.

**Comment by mguinness** [comment]
Also see [Aquacal heater/chiller heat pump with Intellicenter](https://www.troublefreepool.com/threads/aquacal-heater-chiller-heat-pump-with-intellicenter.266373/) thread on TFP regarding RS-485 availability based on installed CPU.
