### ISSUE TITLE
VF pump not working

### ISSUE THREAD

**Issue by omo22** [tagyoureit/nodejs-poolController#355]
**Describe the bug**
VF pump pool button start pump and stop works but irregular may or may not respond to click
the Watt and flow are not displayed NOTHING showing, cant change flow rate
**To Reproduce**

**Expected behavior**

**Screenshots**

**Packet Capture**
will add them,saved on phone but difficult to find, will re do using laptop
Follow the instructions to complete a [packet capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution) and attach the resulting zip/log files.

**Pool Equipment**
stand alone RPI3 connected to VF pump
 - Controller: [e.g. IntelliCenter, EasyTouch, IntelliTouch] not connected dont have a BUS
 - Controller Model: [e.g. IntelliCenter i5PS, EasyTouch2 8P]
 - Controller Firmware Version: [e.g. 1.047]
 - Pump(s) manufacturer and model: [e.g. IntelliFlow 2 VST 011056]
 - Chlorinator: [e.g. iChlor, IntelliChlor-40]
 - Heater(s): [e.g. gas, solar, heatpump, ultratemp]
 - Chemical controller: [e.g. IntelliChem, Relay Equipment Manager (REM)]
 - Valves: [e.g. Intellivalve]
 - Any other relevant equipment:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rstrouse** [comment]
We will need to see a packet capture for this.   If the wattage and flow are not appearing it is likely that we are not sending the override correctly.  When you look at the pump does it say display not active.

**Comment by rstrouse** [comment]
Please upload a replay.  I need to see the messages we are sending to the pump.  In talking with @tagyoureit it appears that VF pumps may need some differences in the communications.   Sometimes it is a little rough because we don't have a particular piece of equipment but it will be telling if we can see the response messages from your pump.

**Comment by omo22** [comment]
[replay (13).zip](https://github.com/tagyoureit/nodejs-poolController/files/7325683/replay.13.zip)

**Comment by tagyoureit** [comment]
When you do your next packet capture, can you start the capture and then stop njsPC.  Wait until the pump display does not say inactive, and then restart njsPC.  I want to see what happens when we first try to communicate with the pump.

**Comment by tagyoureit** [comment]
You didn't pull the latest code.  You are still on 7.4.0 and you should be on 7.5.0.  Please pull the code from Github and repeat the above steps.

**Comment by omo22** [comment]
![image](https://user-images.githubusercontent.com/23144748/137221803-b270bf50-6302-4bb3-aa60-ee370ca1f809.png)
with   7.5   lost dashpanel

**Comment by omo22** [comment]
![image](https://user-images.githubusercontent.com/23144748/137221880-fbde62f6-4a32-461b-9c06-ff416e0b7e53.png)

**Comment by tagyoureit** [comment]
For each application (njsPC, dP, REM) you should follow these directions:
1. `git pull`
2. `npm i`
3. `npm run build` (if your startup scripts are not set to compile each time)

And dashPanel isn't lost because that is what you are showing in the screenshots.  It looks like njsPC didn't start up and you should check the PM2 logs.  `pm2 logs njsPC`.  You can also go into the njsPC directory, (make sure you tell PM2 to not run at the same time - `pm2 stop njsPC`), and try to run it manually to see any errors `npm run start`.

**Comment by tagyoureit** [comment]
Pull again and see if it works.  Any issues, post another packet capture.  I made a few changes.

**Comment by omo22** [comment]
i did git pulll and npm i and run build ......  still same 
I see only watt and g/min, cant change flow rate and switch to different pump circuit e.g cleaning also delay in response 4-6 seconds for on off 
[replay (17).zip](https://github.com/tagyoureit/nodejs-poolController/files/7349906/replay.17.zip)

**Comment by omo22** [comment]
possible cause is that pump on filter mode will not change flow rate, however in manual mode [pump sensors bypassed ] flow rate is editable 
IS THERE option to change mode via dash panel or so?

**Comment by tagyoureit** [comment]
Can you please answer my questions and provide screenshots?

**Comment by omo22** [comment]
wooo i figured out... i started pump on pump feature one and connected wire.. > DISPLAY NOT ACTIVE then it worked..see zip  at leat i can run 2 speeds, i created _+ circuits but could not see them in dash panel created while zip17
[replay (19).zip](https://github.com/tagyoureit/nodejs-poolController/files/7358011/replay.19.zip)

**Comment by omo22** [comment]
i am trying to get video and screenshots from iPhone to send
now Ref to Zip18
Test 1: If you start njsPC, without turning on any circuits, please confirm if you see "Display not active!" on the front panel.
YES
Test 2: Turn on a circuit in njsPC and see if the pump starts.
YES started once pluged but no control except on off
Test 3: Turn on a higher flow circuit and see if the pump changes to the higher speed (if 2+ circuits are on together, the highest 
speed/flow is what is sent to the pumps).
i added x2 circuits + - and SAVED but dont show on dash panel and once go back to pump settings-circuits they are gone nedd to add again ... this process saved on Zip 18
I deleted chrolonator stopped mqtt vera and rem and made pump idle also pump would not delete a schedule it is default and could not disable it inside pump.
I noted that njsPC affected default speed [but no control ]when plugged njsPC while running on manual-mode so I thought I will test it with Feature-1 button running... it works like charm so far except issues with njsPC schedule and water temp not showing.
will add img and video soon showing my DIY RPI  OCP with sensors and relay ready

**Comment by omo22** [comment]
FOLLOWING IMG WHEN TESTD AS ABOVE ZIP18, sorry low img quality from video

![5](https://user-images.githubusercontent.com/23144748/137602221-a220ffa6-3c74-4b83-bea8-7b38c02b04ae.png)
![6](https://user-images.githubusercontent.com/23144748/137602222-18de9663-2630-4be0-9c5c-26c6ae9c292f.png)
![7](https://user-images.githubusercontent.com/23144748/137602223-24870d30-d2a8-4bd6-bfe5-8f994996723b.png)
![8](https://user-images.githubusercontent.com/23144748/137602224-9eea3d19-dcf7-4664-b0b8-04a450c78c51.png)
![9](https://user-images.githubusercontent.com/23144748/137602225-67c8b26f-f726-4621-af64-cbb26190e20c.png)
![10](https://user-images.githubusercontent.com/23144748/137602226-32cf4e6d-d703-4d24-b485-ad728667b87b.png)
![11](https://user-images.githubusercontent.com/23144748/137602227-2bd919e5-8254-49be-b64c-7f09e1957340.png)
![12](https://user-images.githubusercontent.com/23144748/137602229-29c46a90-8d86-46bd-8305-fce1aa249b1f.png)
![13](https://user-images.githubusercontent.com/23144748/137602230-1655e9d9-4e20-40c6-8329-95bfe9057a1d.png)
![1](https://user-images.githubusercontent.com/23144748/137602231-adcbc8ae-1abb-43ec-81dd-0ca90ef89845.png)
![2](https://user-images.githubusercontent.com/23144748/137602233-2e86e4bd-1baa-4a67-b27d-e472506fd96a.png)
![3](https://user-images.githubusercontent.com/23144748/137602234-857a22ef-ed2f-469b-90d8-33f4d6f48c68.png)
![4](https://user-images.githubusercontent.com/23144748/137602236-fe4519ff-61c3-4951-a681-09f4aa12262b.png)

**Comment by omo22** [comment]
following mages when plugged njsPC while pump running on feature-1
![13](https://user-images.githubusercontent.com/23144748/137602266-ef4dafd0-d283-4865-be3c-3e159220e82c.PNG)
![14](https://user-images.githubusercontent.com/23144748/137602267-52cd4891-2a2a-48e0-8dbf-85d7f4c1ffc6.PNG)
![15](https://user-images.githubusercontent.com/23144748/137602270-ef0f4353-241e-4e05-8fa4-d8a5404f3e71.PNG)
![16](https://user-images.githubusercontent.com/23144748/137602271-447f6585-0073-402a-97cf-d364459872d1.PNG)
![17](https://user-images.githubusercontent.com/23144748/137602272-a5ee4685-e7fc-40cd-8e33-968f2c7a34b8.PNG)
![4](https://user-images.githubusercontent.com/23144748/137602273-6312db5a-8628-42bf-81ad-f8ad1e46f151.JPG)
![6](https://user-images.githubusercontent.com/23144748/137602274-f20c0c79-4fd9-4281-bbe0-1d763fd3dbff.JPG)
![6a](https://user-images.githubusercontent.com/23144748/137602276-a8cdce09-b66e-4d29-b9c4-eae878d0547b.JPG)
![1](https://user-images.githubusercontent.com/23144748/137602277-a17b6ae2-19e1-4ec1-ae5b-c800f8d665d0.JPG)
![2](https://user-images.githubusercontent.com/23144748/137602279-493232ff-f0f9-48d8-a1f3-ac57df6cf3bb.JPG)
![3](https://user-images.githubusercontent.com/23144748/137602280-02a9ce97-5967-4e11-952e-e90fcaba878e.JPG)
![7](https://user-images.githubusercontent.com/23144748/137602281-fe792168-bc48-4a6f-852f-92373beb3869.PNG)
![8](https://user-images.githubusercontent.com/23144748/137602282-f31d4d95-b154-456a-9048-21680a824322.PNG)
![9](https://user-images.githubusercontent.com/23144748/137602283-283dff16-f8d4-4320-8573-d2690eb8d203.PNG)
![10](https://user-images.githubusercontent.com/23144748/137602284-559a82c3-3af3-4830-a37f-2dada940fc73.PNG)
![11](https://user-images.githubusercontent.com/23144748/137602285-e286270a-f15c-4419-b9fb-97fbe6d4f412.PNG)
![12](https://user-images.githubusercontent.com/23144748/137602286-925834a2-b96c-4c08-803f-6a1c1fca472b.PNG)

**Comment by omo22** [comment]
I created different circuits e.g 16GPM 24GPM 32GPM etc  all worked perfectly
thanks for the great support.
