### ISSUE TITLE
Capture Manual Priority Override - Intellitouch

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#362]
Please help by doing a [packet capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution) so this feature can be implemented in IntelliTouch. 
![2021-10-29_06-39-37](https://user-images.githubusercontent.com/1646840/139445388-d3873403-0fa0-4167-839f-c33e07dc734b.png)

**Comment by dkroesche** [comment]
I just saw this and can attempt to provide the packet capture if you are still interested.  It looks like this is many months old now.

**Comment by rstrouse** [comment]
Yes please we do not even know where this bit is set in the configuration.

**Comment by dkroesche** [comment]
I am attaching the packet capture.  My "Manual Op Priority" was set to "No".   In the capture,  set it to "Yes" and then set it back to "No"
[replay-2.zip](https://github.com/tagyoureit/nodejs-poolController/files/8240641/replay-2.zip)

**Comment by tagyoureit** [comment]
I just added this.  TYVM for the capture!  Can you please pull the latest and try to set this Settings->General->Delays and see if it picks up the correct status when set from the OCP and sets the correct status when set from njsPC?  

![image](https://user-images.githubusercontent.com/1646840/158816768-ad9590bc-2d69-467c-b914-4aa9f677c161.png)

**Comment by dkroesche** [comment]
Hi -

I pulled the latest code and verified that when I change the state on my controller the changes show up in dash panel.  I also verified that changing the setting in dash panel shows up on my controller.

If you need packet captures for Intellitouch in the future, feel free to send me a note with the issue number.  I don't always look at issues unless I am experiencing issues myself.  :-) 

David
