### ISSUE TITLE
Help with Configuring the Building Automation Card using REM

### ISSUE THREAD

**Issue by rock-crusher** [tagyoureit/nodejs-poolController#366]
Ok, so I believe I finally have all the requisite software installed and running when the Raspberry Pi starts up. I enabled REM in njsPC as per outlined in the “Configuring the Software” procedure. I am now at the procedure of “Configure the Building Automation Card”. The procedure says to: “from a browser window type http://<ip address of the pi>:8080. A webpage will appear to allow configuration of the devices on the Pi.” This “webpage to allow configuration of the devices on the Pi” does not appear at all, at least not for me. However, as per rstrouse (thanks again sir) http://raspberrypi:8080 will give me access to allow configuration of the REM. Unfortunately, I can’t seem to manipulate any of the fields, but again I have no experience with this and could sure use some help getting this completed. The attached image is what I get, but I can’t seem to do much with it?

![REM screen shot](https://user-images.githubusercontent.com/94593954/142708242-d6eadb7b-65b5-4f7e-a672-d41143102e04.JPG)

**Comment by rstrouse** [comment]
First click the + on the i2c buses list and click create bus.  Do not change the bus number as the default I2c bus is 1.  This will add a tab across the top.  After you do this select that tab and follow these instructions.

https://github.com/rstrouse/relayEquipmentManager/wiki/Sequent-Microsystems-Boards#sequent-building-automation-hat-mega-bas

**Comment by rstrouse** [comment]
I am closing this for now.  If you have any other questions go ahead and submit another issue.
