### ISSUE TITLE
AutoBackup causing error

### ISSUE THREAD

**Issue by bad350trk** [tagyoureit/nodejs-poolController#370]
I am getting an error after turning on AutoBackups.  I get the general error shown in the screen shot below, and the Backups tab is completely blank now.

![Backup Error](https://user-images.githubusercontent.com/25586223/143775627-be610372-d373-4140-a8ee-a16990dade75.png)

Am unable to recreate the issue to get a replay capture because the Backups tab is empty.

**Pool Equipment**
 - Controller: IntelliCenter
 - Controller Model: IntelliCenter i8PS
 - Controller Firmware Version: 1.047
 - Pump(s) manufacturer and model: IntelliFlow 2 VST 011056
 - Chlorinator: IntelliChlor-40
 - Heater(s): MasterTemp 400
 - Chemical controller: N/A
 - Valves: Intellivalve
 - Any other relevant equipment:

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.45 (Official Build) (64-bit)

Thanks,

--Jeff

**Comment by rstrouse** [comment]
Upload your config.json file.  You can rename it to config.txt so that it uploads.   The servers element is probably null instead of `"servers": []`.

**Comment by bad350trk** [comment]
Here is the config.json file.

[config.txt](https://github.com/tagyoureit/nodejs-poolController/files/7614217/config.txt)

Although, I did a git pull and now it all appears to be functioning.

Thanks,

--Jeff

**Comment by rstrouse** [comment]
Yep I fixed the code so that it defaults the servers if they do not exist.  Your file confirms that to be the case when there are no REM servers to backup or restore.

**Comment by bad350trk** [comment]
Sweet!  Thanks!

--Jeff
