### ISSUE TITLE
LOW PRIORITY - sometimes DashPanel stays tuck at 'Loading 0%' during a service restart even though dash/nsjpc is fully loaded

### ISSUE THREAD

**Issue by johnny2678** [tagyoureit/nodejs-poolController#377]
I frequently get this at the top right of dashpanal
![image](https://user-images.githubusercontent.com/8219743/149027988-db597759-1f16-426d-9210-61e7c767c111.png)

doesn't happen every time njspc restarts, but sometimes.

managed to get a replay the last time it happened:
[replay (28).zip](https://github.com/tagyoureit/nodejs-poolController/files/7850127/replay.28.zip)

**Comment by johnny2678** [comment]
This is still happening on the latest version of dash/njspc.  Doesn't look like any functionality is affected but still get `Loading 0%` sometimes after start up.

still not important but let me know if there's any other information I can provide.

**Comment by tagyoureit** [comment]
I took a look and noticed inbound MQTT requests being processed before the system is ready.   These are:

```
[1/11/2022, 4:57:11 PM] debug: MQTT: Inbound pool/easytouch2-4/state/feature/setState: {"id":15,"isOn":"on"}
[1/11/2022, 4:57:11 PM] debug: MQTT: Inbound pool/easytouch2-4/state/circuit/setState: {"id":2,"isOn":"off"}
...
[1/11/2022, 4:57:11 PM] debug: MQTT: Inbound pool/easytouch2-4/config/chemController: {"id":50,"alkalinity":65}
...
[1/11/2022, 4:57:11 PM] debug: MQTT: Inbound pool/easytouch2-4/state/chlorinator: {"id":1,"poolSetpoint":0}
```

This has the side effect of loading up the internal pool objects before they are fully initialized.  I added code to ignore any inbound MQTT requests until the system is initialized.  Can you pull and try again?  

If this works, we should do the same for the api's.  Let me know how this works.  Thanks for your patience.

**Comment by johnny2678** [comment]
Closing this... haven't noticed the percentage getting stuck in a few releases now. Thx!
