### ISSUE TITLE
Add BAS Watchdog code

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#381]
REM, copy from Super Watchdog to BAS.

**Comment by tagyoureit** [comment]
And to the IND.

**Comment by DrJeff** [comment]
Does the watchdog work inside of REM I don't see how to add it on the BAS board. There is a separate menu and also a tab not sure how to make it work though.

**Comment by rstrouse** [comment]
No we haven't gotten to it yet.  Its function is a bit dubious though so I am not sure it gains the value that you might think.
