### ISSUE TITLE
RS485 Communication Issue after Controller, Dashboard and REM update

### ISSUE THREAD

**Issue by john800xc** [tagyoureit/nodejs-poolController#391]
**Describe the bug**
I have the Pi, MEGA-BAS and 8 relay hat running pool controller, REM and dash panel. All was well, I had the RS485 connection running my pool pump flawlessly for a couple weeks. It is also currently still connected and controlling my pool valves, heater and receiving temp info from my two sensors. However..

After updating the pool controller and associated software I am having RS485 communication issues. 

**To Reproduce**
Restarting the Pi and updating software has not helped. I am getting the error. It does this error repeatedly now. 

**Expected behavior**
Connect to pump via RS485. 

**Screenshots**
Photos of the error in the controller screen and on the dash panel. 
![NEW](https://user-images.githubusercontent.com/100490298/155857000-dcf63a64-f8b8-4727-af95-ab67cc61b55f.JPG)
![Rs485](https://user-images.githubusercontent.com/100490298/155857002-a4d281b2-273f-43e8-9971-5842297c98b9.JPG)

**Packet Capture**
Attached. 
[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/8147390/replay.zip)

**Pool Equipment**
No Controller, only RS485 device is my

 Intelliflo VS pump 
Heater(s): gas heater
Valves: 3 Intellivalves

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS for controller and Windows 10 to access dash panel
 - Browser: Chjrome
 - Version - Latest

**Comment by john800xc** [comment]
1. Wiring checks out. 
2. Completed the firmware update successfully. 

Now, I think I have an issue with the REM install on my Pi. Forgive my ignorance. I now can not access REM. I am getting this error below. Before, when I only had the RS485 error I was able to get into REM and make sure the pass thru was checked and I was snooping around looking for something I inadvertently checked or missed, well, I must have done something that screwed up REM. I wish I could explain further but that's all I know.

![REM Error](https://user-images.githubusercontent.com/100490298/155861279-5332384c-e7f3-4f26-8d66-8a16963e1f23.JPG)

**Comment by rstrouse** [comment]
I saw your post on TFP so I would like you to run the following command.
`nvm i 14.7.0`

This should get you back to matching versions on npm and nvm.

Then run `npm i` again to install all the other dependencies.

**Comment by john800xc** [comment]
The nvm i 14.7.0 command was successful. 

After the npm i command I got:
![NPM I](https://user-images.githubusercontent.com/100490298/155896300-a14afb2b-29f8-480e-b736-ffa8b7f9ff90.JPG)

Now REM log error is different. This repeats. 
![REM LOg](https://user-images.githubusercontent.com/100490298/155896309-212e1e4d-77a2-4b13-86c4-9ac568bc53be.JPG)

**Comment by rstrouse** [comment]
Ok now run the following commands.
`cd ~/relayEquipmentManager`
`pm2 stop REM`
`npm i`
`npm rebuild`
`pm2 restart REM`

You may need to do this for the nodejs-poolController and the nodejs-poolController-dashPanel apps as well.  Just use njsPC and dashPanel in the pm2 commands.  If you get a message that it doesn't recognize the pm2 command simply close the command window and open another one.  It will then have the proper path statements.  This is because some of the libraries overwrite the path searching variables.

**Comment by john800xc** [comment]
I was able to do all three and it all seemed to work. However, when running the npm i command on both the REM and poolController I get these errors. It did not happen on the dashPanel if it matters. 

Their are many more but here are three and they seem to be indicating node and NPM being too old of versions? 
![install errors](https://user-images.githubusercontent.com/100490298/155899201-3c57c812-26f0-44f1-a534-bf29d3dfb46d.JPG)

REM is still giving the same error. 
![REM logggg](https://user-images.githubusercontent.com/100490298/155899225-9600dc4d-46db-459f-9f4d-a4475e7f9926.JPG)

**Comment by rstrouse** [comment]
I am such a goof I meant to tell you to run `nvm i 14.17.0`.  However, those warnings are not really relevant.  If this command does not come back with Now using node v14.17.0 (npm 8.5.2) then it is not updating the node version.

**Comment by tagyoureit** [comment]
You might just want to delete the entire `node_modules` directory and run `npm i` again.  Sometime node won't update the dependencies if you change node versions and that might be happening here.

**Comment by john800xc** [comment]
Thanks guys. I got it worked out. I wish I knew exactly what did it but my button smashing finally worked!
