### ISSUE TITLE
EasyTouch4P Stopped working after updating to hash 65371696b4c2707d38ba699052da304e12d0770f

### ISSUE THREAD

**Issue by terafin** [tagyoureit/nodejs-poolController#395]
**Describe the bug**
My pool lights and relays were working wonderfully (thanks again!) until I updated to today's build as of this hash: https://github.com/tagyoureit/nodejs-poolController/commit/65371696b4c2707d38ba699052da304e12d0770f.

Since that, all my commands from the web interface (and API) fail, but the UI/API do get updates from the EasyTouch4P.

```
MessageMessage aborted after 4 attempt(s): 165,1,16,16,134,2,3,1,1,82
```

I reverted to a hash as of here: https://github.com/tagyoureit/nodejs-poolController/commit/c563c94a51d9616ab396fa32ab853f223262c80e

Verified things work flawlessly again.

**To Reproduce**
1. Update to latest mimi docker
2. Try to use circuits. Fails
3. Downgrade to mimi's docker, 7.6.1, succeeds.

Note I haven't tried with git checkouts yet... (just now how I have setup my pi... so it's possible there's a docker build issue?)

**Packet Capture**
Follow the instructions to complete a [packet capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution) and attach the resulting zip/log files.
[replay.zip](https://github.com/tagyoureit/nodejs-poolController/files/8249273/replay.zip)

**Comment by terafin** [comment]
Did some manual checkouts to help bisect, this is the commit that broke things for me:
https://github.com/tagyoureit/nodejs-poolController/commit/88d18b97d85cf68f8851c7ad5dfd5920f2887a87

**Comment by rstrouse** [comment]
Sorry I did not see this message right away sometimes github doesn't send me info right away.  The issue was related to the added protocols for the RS485.  It seems that our calls for the outbound to ET was talking to itself.  Source 16 to destination 16.  Please pull njsPC and let me know how it goes.

**Comment by terafin** [comment]
Fixed it, thanks!
