### ISSUE TITLE
Will this work with an Pentair EasyTouch controller?

### ISSUE THREAD

**Issue by dhop90** [tagyoureit/nodejs-poolController#44]
I'm currently using the ScreenLogic2 protocol adapter but would like to install this nodejs-poolController on a raspberry PI and integrate it with the smartthings hub and app.

Using the REST URI, it should be pretty easy to code up a smartthings app

**Comment by tagyoureit** [comment]
Yup, it should work fine with EasyTouch.  You will probably have less circuits/schedules but everything else should be ok.  

And you can definitely roll your own smartthings integration.  Check out the samples in the integrations directory.
