### ISSUE TITLE
Cool setpoint missing on Spa

### ISSUE THREAD

**Issue by Tegguy** [tagyoureit/nodejs-poolController#443]
### nodejs-poolController Version/commit

7.61

### nodejs-poolController-dashPanel Version/commit

7.61

### Are you using Docker?

- [ ] Yes.

### What steps will reproduce the bug?

On the dashpanel under the Spa display the "cool setpoint" is missing for the ultratemp heater. I can see the heat setpoint but not the cool.

### What happens?

Missing setpoint display

### What should have happened?

Setpoint should display

**Comment by tagyoureit** [comment]
Can you attach a packet capture replay?

**Comment by Tegguy** [comment]
The setpoint is there and working and even pops up when enabling ultratemp
but the value doesn't display on the dashpanel

**Comment by rstrouse** [comment]
Pull dashPanel the setpoint should appear if you are not on an EasyTouch or IntelliTouch panel.   These for some odd reason don't support the cooling setpoint on the second body.  Changes to the second body cooling setpoint end up on the first body.

**Comment by Tegguy** [comment]
Got it thanks!
