### ISSUE TITLE
[BUG] Manually cancelling super chlorinate doesn't not return SWG to original output

### ISSUE THREAD

**Issue by Crewski** [tagyoureit/nodejs-poolController#468]
### nodejs-poolController Version/commit

f7a439a

### nodejs-poolController-dashPanel Version/commit

f8c00dd

### Are you using Docker?

- [ ] Yes.

### Chlorinator(s)

Aquarite T-9

### What steps will reproduce the bug?

After cancelling an in-progress super chlorinate session via dashPanel or Mqtt (config/chlorinator), the output will remain at 100% instead of reverting back to the previous setpoint.

### What happens?

Starting point:
![image](https://user-images.githubusercontent.com/8012153/171169588-1182eb80-8b32-4db3-ab6c-a8f88e4be118.png)

Super Chlorinate:
![image](https://user-images.githubusercontent.com/8012153/171169707-f8e5205e-3bfb-4980-bf57-3252dbd59699.png)

After cancelling:
![image](https://user-images.githubusercontent.com/8012153/171170013-08ae07fc-6516-4517-80f9-310afa433528.png)

### What should have happened?

The SWG output should return to the pre-super chlorinate value.....30% in this example.

### Additional information

This replay has me turning super chlorinate on and off via dashPanel.

[replay (2).zip](https://github.com/tagyoureit/nodejs-poolController/files/8804956/replay.2.zip)

**Comment by rstrouse** [comment]
What do you have on the other end of MQTT that is changing the physical setpoint from the endpoint.  This is why it is not returning to the original 30%.  Because the external interface is changing the physical setpoint to 100%.  From your logs after you engage superChlor.
`[5/31/2022, 07:56:54] debug: MQTT: Inbound pool/state/chlorinator: {"id":1,"poolSetpoint":"100.0"}`

**Comment by Crewski** [comment]
OK, you are exactly right.  The problem was with code to sync up with Home Assistant.  I'll have to put a little more thought into i on my end.  This also fixes the turning the pool on/off issue.
