### ISSUE TITLE
Timezone & Locality 'Units' option not available in 7.7.0

### ISSUE THREAD

**Issue by theRealMCQwerty** [tagyoureit/nodejs-poolController#510]
Didn't want to log this as a bug as it appears to be working for others. Not sure if this is a Nixie only feature or if it can be done for my Intellicenter i8PS?

I saw this issue as I would like to set my temp units to deg C: https://github.com/tagyoureit/nodejs-poolController/issues/341

I updated and am currently running v 7.7.0 (see screenshot)
![image](https://user-images.githubusercontent.com/26889036/176244832-4e066918-2b07-478b-a63b-115be3d27e73.png)

But I haven't got the 'Units' option in the Timezone and Locality settings (see screenshot)
![no option](https://user-images.githubusercontent.com/26889036/176245095-43ac9a7b-fb5a-42b8-a0fb-dacc0f84273b.PNG)

Thanks

**Comment by theRealMCQwerty** [comment]
@rstrouse ah bummer. Could the temp conversion be done on the fly in the UI only?

**Comment by rstrouse** [comment]
Have you checked the OCP?  Maybe that option is an OCP only option.
