### ISSUE TITLE
Node versions?

### ISSUE THREAD

**Issue by bsileo** [tagyoureit/nodejs-poolController#56]
What version(s) of Node and NPM are you working with? My environment is on a Raspberry Pi (I have a 2B+ and a 3 zero) but so far I am running into version compatibility issues when trying things with node-red and newer Node 8 environments.

**Comment by tagyoureit** [comment]
I'm running v4.  It should work on newer versions.  But I think node-red might be a bit older.  Try v4 or v6 and it should be good to go.
