### ISSUE TITLE
Console, Continual Message(s)

### ISSUE THREAD

**Issue by arrmo** [tagyoureit/nodejs-poolController#61]
Hi,

Filling the logs and console with the following message it seems (every minute),
`16:40:41.769 INFO CHECKING DELAY!  0
`

Perhaps make this one Debug level?

Thanks!

**Comment by tagyoureit** [comment]
Removed... yes, that one should not be there.

**Comment by arrmo** [comment]
Thanks! Is this fix in the latest 4.x-DEV branch?

**Comment by tagyoureit** [comment]
It's fixed on my machine... will be pushed up with the next check in.
