### ISSUE TITLE
Panel re-order broken

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#62]
I can re-order the panels within each browser window.  But when reloading them the next time, they are back to the default order.

**Comment by arrmo** [comment]
NP, working on it. Moving files to assets seems to have broken things here though - re-trenching again.

**Comment by arrmo** [comment]
OK, got it working here, but a couple questions first,
1) Did you move the systeminformation anchor outside the draggablePanelList? I thought you had, but don't see it in the code I pulled. It's key to this.
2) I seem to have to add ../ in front of all my links to stylesheets and code. Do you see this also?

Thanks!

**Comment by tagyoureit** [comment]
1.  No, it's right below it in my (current) code.
2.  I haven't seen this either.  I was messing around with a couple of them, but it didn't appear to make a difference.  Obviously, it does and I missed it.

Can you attach a working version of the file here and I'll try it tomorrow?  I have a bunch of other off-line edits that I'm working on so merging the code might be tricky.

Thanks!

**Comment by arrmo** [comment]
For 1), try swapping the order (i.e. as below) - this way the anchor is outside the draggable list.
<a name="systeminformation" class="anchor"></a>
<div id="draggablePanelList">

I think this is all you need to get the order restore working again - please let me know.

On 2), let's revisit after your updates.

Thanks!


PS: I'm not sure if Hide is what we want for the Release Details ... rather, once read, then put them away until new info comes - right? Separate ticket for this?

**Comment by tagyoureit** [comment]
See attached for my order.  systeminformation is inside the draggablePanelList... 

![screen shot 2017-11-29 at 8 59 34 pm](https://user-images.githubusercontent.com/1646840/33414923-825341b4-d548-11e7-9084-e881011c6c2e.png)

(new thread for release notes created...)

**Comment by arrmo** [comment]
Yep, that's what I was trying to say above - change the order, like this,
```
<a name="systeminformation" class="anchor"></a>
<div id="draggablePanelList">
```

Then, does panel restore work for you?

**Comment by tagyoureit** [comment]
Ah!  Yes... good to go on this one.  Thanks!

**Comment by arrmo** [comment]
Excellent! So you'll include this correction, right? Just want to make sure one of us does ... :-).
