### ISSUE TITLE
Treatment for Release panel in UI

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#63]
Thoughts on how to treat this?  We could make it "permanently" disappear, and I'm open here, but hiding it now wouldn't be any different from the version notification.  Shouldn't they be treated the same?  And no one has really complained about that because resetting the UI shouldn't be done that often.

**Comment by arrmo** [comment]
Somehow we need to flag text as read, and redisplay when the text changes ... sort of a notification, and then "Hey, I've read this one" ... agreed? I admit, I'm not looking for it to just stay there after I've seen it, but also - don't hide it forever (like happens when I hit hide).

Agreed?
