### ISSUE TITLE
[BUG] Intellichem Tank Level reset to 0

### ISSUE THREAD

**Issue by snagytx** [tagyoureit/nodejs-poolController#631]
### nodejs-poolController Version/commit

7.7.0/79f330b

### nodejs-poolController-dashPanel Version/commit

7.7.0/0193678

### relayEquipmentManager Version/commit

none

### Node Version

docker

### Platform

docker

### RS485 Adapter

Wlfin

### Are you using Docker?

- [X] Yes.

### OCP

Intellicenter i5PS

### Pump(s)

Intelliflo VS & WisperFlow

### Chlorinator(s)

Intellichem

### What steps will reproduce the bug?

Reset Alkalinity Level

### What happens?

The Tank Level for ORP and Acid are reset to 0

### What should have happened?

The Tank Level for ORP and Acid should remain untouched

### Additional information

When I change the alkalinity this message is sent:

PUT http://XXXX:4200/state/chemController
`{"id":1,"ph":{"setpoint":7.5,"dailyVolumeDosed":1000},"orp":{"setpoint":700,"dailyVolumeDosed":10},"alkalinity":95,"calciumHardness":350,"cyanuricAcid":40,"borates":0,"saturationIndex":"-0.1"}`

In messageManager I see:

![image](https://user-images.githubusercontent.com/10343781/201480028-2dbe895c-f01d-4aee-93a9-bbb5a521e4b4.png)
![image](https://user-images.githubusercontent.com/10343781/201480010-f878043c-abf2-4aca-845c-e603ba1b9e19.png)

**Comment by rstrouse** [comment]
I posted up a change that I think fixes the issue.  However, I never did get a replay from somebody with IntelliChem while the tank levels were adjusted from IntelliChem.  At the time I think that the IntelliCenter web app was not working for this function.   
Can I get a replay where you set the tank levels from IntelliCenter?  

The message will look something like below where byte indexes 11 and 12 define the tank level + 1.  So byte 11 set to 7 means the tank level is 6 in IntelliChem for pH (byte[11]) and 0 for chlorine (byte[12]).
![image](https://user-images.githubusercontent.com/47839015/201534830-60c7b2c7-ca57-4bf6-8534-3ca8475d8d63.png)

**Comment by snagytx** [comment]
You can't set the tank level from IntelliCenter. But you can adjust the Alkalinity, Calcium Hardness and Cyanuric Acid level.

I ran a test to increase Alkalinity from 80 to 81:
![image](https://user-images.githubusercontent.com/10343781/201669948-5f955f39-eba3-4f29-bcd6-38e024c3dbad.png)
response:
![image](https://user-images.githubusercontent.com/10343781/201670013-a499c90b-a5cf-4a6b-855b-1d71603d9525.png)

Calcium Hardness from 350 to 351:
![image](https://user-images.githubusercontent.com/10343781/201670080-5b8fb7bf-96c0-4440-998e-755e94f92eb1.png)
response:
![image](https://user-images.githubusercontent.com/10343781/201670129-cd8e0f36-8b23-41c6-b95b-0c7e616b8fe8.png)

Cyanuric Acid from 40 to 41:
![image](https://user-images.githubusercontent.com/10343781/201670290-0acbcfe3-a79f-4437-b397-fbdcc6ca9cf5.png)
response:
![image](https://user-images.githubusercontent.com/10343781/201670332-6252bac5-ee85-4a3f-8764-f658a7060fb2.png)


The actual Chlorine Tank level is 4 while the Acid tank level is 2. Since they can't be tweaked from the web UI, I cant capture that. But I went outside and adjusted the Tank levels from IntelliCenter directly and I got:

For Chrorine - changed from 2 to 3:
![image](https://user-images.githubusercontent.com/10343781/201671633-20a6eba3-ef8b-45de-88a8-dddfe42fd8d1.png)
Response:
![image](https://user-images.githubusercontent.com/10343781/201671682-d754d3ce-8440-45a8-b773-bf3be7b3cedd.png)

Acid - changed from 4 to 5:
![image](https://user-images.githubusercontent.com/10343781/201671765-fd37ac0b-a3f5-4479-bd9b-e70ba03de1cc.png)
Response:
![image](https://user-images.githubusercontent.com/10343781/201671827-3c1600cd-5d9f-403b-9d95-c5dec6815994.png)

**Comment by tagyoureit** [comment]
The screenshots are helpful, but @rstrouse is referring to a [packet capture](https://github.com/tagyoureit/nodejs-poolController/wiki/How-to-capture-all-packets-for-issue-resolution#-dashpanel). Can you turn on the capture and run the same exact scenario and then upload the resulting files?  Often we can see what's going on with the packets and pick up nuances that are otherwise not available to us just by screen shots. But it does sound like you are on the right track.

**Comment by snagytx** [comment]
I have I have dropped all numbers by 1 unit. See attached the logs.
[replay (1).zip](https://github.com/tagyoureit/nodejs-poolController/files/10003950/replay.1.zip)

**Comment by rstrouse** [comment]
Did you pull the changes from the repo before running the capture?  I believe you should be able to even set the tank levels from dashPanel if you click/tap on the tank.   The output from njsPC is identical to the setting changes from IntelliCenter but only if you pull the latest code.

**Comment by snagytx** [comment]
my bad, I bad, I didn't pull the latest docker image, from the screenshots it seemed that the OCP sends to Chem to set bytes 4 & 5, not 11 & 12, I though that the change would work, I should have still pulled and tested.

I just did that and it seems to work to asjust Alkalinity, Calcium Hardness, Cyanuric Acid and Tank levels.

**Comment by rstrouse** [comment]
Awesome.  It looks like you can actually set tank levels from njsPC but not IntelliCenter... funny.

Keep in mind that there are more than one conversation going on with the messages related to IntelliChem.

1. There is the conversation between any external controller to the OCP.  This communication is done through action 168 messages with the first two bytes being [8, 0] and the responses from action 30 and 222 with the first two bytes being [8, 0] and [8, 1].  This is the conversation we are concerned with.
2. Then the OCP communicates with IntelliChem using action 210 with a response of action 18 to get the status.  When the OCP sets a value to IntelliChem it sends this on action 146 and simply gets an ACK response when IntelliChem receives it.

The conversation from your screenshots above is the one between IntelliChem and the OCP.  The messageManager filter should allow you to identify the proper conversations in the filter.
