### ISSUE TITLE
Yet Another Smartthings UI announcement

### ISSUE THREAD

**Issue by dhop90** [tagyoureit/nodejs-poolController#67]
Not to be out done by [bsileo](https://github.com/bsileo/SmartThings_Pentair), I created my own smartthings app.

![](https://github.com/dhop90/pentair-pool-controller/blob/master/images/IMG_6035.PNG)

check it out [here](https://github.com/dhop90/pentair-pool-controller/blob/master/README.md)

**Comment by tagyoureit** [comment]
Very cool!  I will really need to get a SmartThings app now.  (BTW, just check your spelling... "What is the Smartthing Penatair Pool Controller").

**Comment by arrmo** [comment]
Just a thought, and this definitely @tagyoureit 's call, but ... I think we need to have a consistent and defined interface on the nodejs-poolController side (so it's the same for any and all ST apps). Agreed?

Is this the case here?

**Comment by tagyoureit** [comment]
Well, from my end, it's only 1 interface.  :)  But I'm all for consistency.  @dhop90, how is your implementation different from @bsileo?  I have played with his, but have not yet (but would like to) check out yours.

**Comment by tagyoureit** [comment]
Added to readme, so removing from the issues list.
