### ISSUE TITLE
Fix bootstrap pump update

### ISSUE THREAD

**Issue by tagyoureit** [tagyoureit/nodejs-poolController#76]
The pumps sometimes add additional pumps instead of updating them as seen in the picture below.  
![screen shot 2017-12-28 at 10 49 04 pm](https://user-images.githubusercontent.com/1646840/34431147-6cfe26e0-ec21-11e7-8341-3c0b4b0ec866.png)

**Comment by johnny2678** [comment]
I can confirm this.  I've noticed it as well.  Goes away with a refresh.

**Comment by tagyoureit** [comment]
This was fixed with 5.1.0.
