### ISSUE TITLE
Second pump set to "None" causes errors

### ISSUE THREAD

**Issue by rjsears** [tagyoureit/nodejs-poolController#83]
In the config file, if "type": "None" is set it errors out, but setting "type": "none" works just fine.

"2": {
                "type": "none",
                "externalProgram": {
                    "1": -1,
                    "2": -1,
                    "3": -1,
                    "4": -1
                },
                "friendlyName": "",
                "id": {
                    "productName": "",
                    "productNumber": "",
                    "manufacturer": "",
                    "description": ""
                }
            }

**Comment by tagyoureit** [comment]
I believe I fixed this not too long ago.
