### ISSUE TITLE
Not an issue a new Plugin

### ISSUE THREAD

**Issue by sjpbailey** [tagyoureit/nodejs-poolController#917]
## 💥 i have written and released version one of NixieSingle on Universal Devices.
Plugin is free forUDI customers.

https://polyglot.universal-devices.com/nsinfo/09da8fd9-25d7-44db-b48c-44a976cc02f2%2FProduction

python code for plugin here.
https://github.com/sjpbailey/udi-nodejs-pool-Nixie-Single-V3

Have a wonderful day.

**Comment by tagyoureit** [comment]
I added this to the [Wiki homepage](https://github.com/tagyoureit/nodejs-poolController/wiki).  I suggest you also put this in the [Discussions](https://github.com/tagyoureit/nodejs-poolController/discussions) area.  There were at least a few old time ISY users in there that might be interested in this.   Closing for now.
